// Auto-generated by _gen_high103_aggregator.cjs — high 103-pass top-ups (PARTIAL: 183/238).
// Merged into high catalogs by loadQuestionCatalog (appended to matching trackId).
import type { Question } from './types'
import { alevelBiologyHigh103TopUpAQuestions } from './alevelBiologyHigh103TopUpA'
import { alevelBiologyHigh103TopUpBQuestions } from './alevelBiologyHigh103TopUpB'
import { alevelChemistryHigh103TopUpAQuestions } from './alevelChemistryHigh103TopUpA'
import { alevelChemistryHigh103TopUpBQuestions } from './alevelChemistryHigh103TopUpB'
import { alevelComputerScienceHigh103TopUpAQuestions } from './alevelComputerScienceHigh103TopUpA'
import { alevelComputerScienceHigh103TopUpBQuestions } from './alevelComputerScienceHigh103TopUpB'
import { alevelEconomicsHigh103TopUpAQuestions } from './alevelEconomicsHigh103TopUpA'
import { alevelEconomicsHigh103TopUpBQuestions } from './alevelEconomicsHigh103TopUpB'
import { alevelEnglishHigh103TopUpAQuestions } from './alevelEnglishHigh103TopUpA'
import { alevelEnglishHigh103TopUpBQuestions } from './alevelEnglishHigh103TopUpB'
import { alevelPhysicsHigh103TopUpAQuestions } from './alevelPhysicsHigh103TopUpA'
import { alevelPhysicsHigh103TopUpBQuestions } from './alevelPhysicsHigh103TopUpB'
import { apEuropeanHistoryHigh103TopUpQuestions } from './apEuropeanHistoryHigh103TopUp'
import { apPsychologyHigh103TopUpQuestions } from './apPsychologyHigh103TopUp'
import { biology_2eHigh103TopUpAQuestions } from './biology_2eHigh103TopUpA'
import { biology_2eHigh103TopUpBQuestions } from './biology_2eHigh103TopUpB'
import { col10thGradeReadingAndVocabHigh103TopUpAQuestions } from './col-10th-grade-reading-and-vocabHigh103TopUpA'
import { col10thGradeReadingAndVocabHigh103TopUpBQuestions } from './col-10th-grade-reading-and-vocabHigh103TopUpB'
import { col7thGradeMathHigh103TopUpAQuestions } from './col-7th-grade-mathHigh103TopUpA'
import { col7thGradeMathHigh103TopUpBQuestions } from './col-7th-grade-mathHigh103TopUpB'
import { col7thGradeNyNextGenHigh103TopUpAQuestions } from './col-7th-grade-ny-next-genHigh103TopUpA'
import { col7thGradeNyNextGenHigh103TopUpBQuestions } from './col-7th-grade-ny-next-genHigh103TopUpB'
import { col7thGradeReadingAndVocabHigh103TopUpAQuestions } from './col-7th-grade-reading-and-vocabHigh103TopUpA'
import { col7thGradeReadingAndVocabHigh103TopUpBQuestions } from './col-7th-grade-reading-and-vocabHigh103TopUpB'
import { col8thGradeMathHigh103TopUpAQuestions } from './col-8th-grade-mathHigh103TopUpA'
import { col8thGradeMathHigh103TopUpBQuestions } from './col-8th-grade-mathHigh103TopUpB'
import { col8thGradeNyNextGenHigh103TopUpAQuestions } from './col-8th-grade-ny-next-genHigh103TopUpA'
import { col8thGradeNyNextGenHigh103TopUpBQuestions } from './col-8th-grade-ny-next-genHigh103TopUpB'
import { col8thGradeReadingAndVocabHigh103TopUpAQuestions } from './col-8th-grade-reading-and-vocabHigh103TopUpA'
import { col8thGradeReadingAndVocabHigh103TopUpBQuestions } from './col-8th-grade-reading-and-vocabHigh103TopUpB'
import { col9thGradeReadingAndVocabHigh103TopUpAQuestions } from './col-9th-grade-reading-and-vocabHigh103TopUpA'
import { colALevelBiologyHigh103TopUpAQuestions } from './col-a-level-biologyHigh103TopUpA'
import { colALevelBiologyHigh103TopUpBQuestions } from './col-a-level-biologyHigh103TopUpB'
import { colALevelEconomicsHigh103TopUpAQuestions } from './col-a-level-economicsHigh103TopUpA'
import { colALevelEconomicsHigh103TopUpBQuestions } from './col-a-level-economicsHigh103TopUpB'
import { colALevelMathsHigh103TopUpAQuestions } from './col-a-level-mathsHigh103TopUpA'
import { colALevelMathsHigh103TopUpBQuestions } from './col-a-level-mathsHigh103TopUpB'
import { colAlgebra1NyNextGenHigh103TopUpAQuestions } from './col-algebra-1-ny-next-genHigh103TopUpA'
import { colAlgebra1NyNextGenHigh103TopUpBQuestions } from './col-algebra-1-ny-next-genHigh103TopUpB'
import { colAlgebraBasicsHigh103TopUpAQuestions } from './col-algebra-basicsHigh103TopUpA'
import { colAlgebraBasicsHigh103TopUpBQuestions } from './col-algebra-basicsHigh103TopUpB'
import { colApArtHistoryHigh103TopUpQuestions } from './col-ap-art-historyHigh103TopUp'
import { colApBiologyHigh103TopUpQuestions } from './col-ap-biologyHigh103TopUp'
import { colApCalculusHigh103TopUpQuestions } from './col-ap-calculusHigh103TopUp'
import { colApChemistryHigh103TopUpQuestions } from './col-ap-chemistryHigh103TopUp'
import { colApComputerSciencePrinciplesHigh103TopUpAQuestions } from './col-ap-computer-science-principlesHigh103TopUpA'
import { colApComputerSciencePrinciplesHigh103TopUpBQuestions } from './col-ap-computer-science-principlesHigh103TopUpB'
import { colApComputerScienceHigh103TopUpQuestions } from './col-ap-computer-scienceHigh103TopUp'
import { colApEconomicsHigh103TopUpQuestions } from './col-ap-economicsHigh103TopUp'
import { colApEnglishLiteratureHigh103TopUpQuestions } from './col-ap-english-literatureHigh103TopUp'
import { colApMacroeconomicsHigh103TopUpAQuestions } from './col-ap-macroeconomicsHigh103TopUpA'
import { colApMacroeconomicsHigh103TopUpBQuestions } from './col-ap-macroeconomicsHigh103TopUpB'
import { colApMicroeconomicsHigh103TopUpAQuestions } from './col-ap-microeconomicsHigh103TopUpA'
import { colApMicroeconomicsHigh103TopUpBQuestions } from './col-ap-microeconomicsHigh103TopUpB'
import { colApPhysicsHigh103TopUpQuestions } from './col-ap-physicsHigh103TopUp'
import { colApUSHistoryHigh103TopUpQuestions } from './col-ap-u-s-historyHigh103TopUp'
import { colApUsGovernmentPoliticsHigh103TopUpQuestions } from './col-ap-us-government-politicsHigh103TopUp'
import { colApUsHistoryHigh103TopUpAQuestions } from './col-ap-us-historyHigh103TopUpA'
import { colApUsHistoryHigh103TopUpBQuestions } from './col-ap-us-historyHigh103TopUpB'
import { colApWorldHistoryHigh103TopUpQuestions } from './col-ap-world-historyHigh103TopUp'
import { colArtHistoryHigh103TopUpAQuestions } from './col-art-historyHigh103TopUpA'
import { colArtHistoryHigh103TopUpBQuestions } from './col-art-historyHigh103TopUpB'
import { colClimateProjectHigh103TopUpAQuestions } from './col-climate-projectHigh103TopUpA'
import { colClimateProjectHigh103TopUpBQuestions } from './col-climate-projectHigh103TopUpB'
import { colComputerProgrammingHigh103TopUpAQuestions } from './col-computer-programmingHigh103TopUpA'
import { colComputerProgrammingHigh103TopUpBQuestions } from './col-computer-programmingHigh103TopUpB'
import { colComputerScienceTheoryHigh103TopUpAQuestions } from './col-computer-science-theoryHigh103TopUpA'
import { colComputerScienceTheoryHigh103TopUpBQuestions } from './col-computer-science-theoryHigh103TopUpB'
import { colComputersAndTheInternetHigh103TopUpAQuestions } from './col-computers-and-the-internetHigh103TopUpA'
import { colComputersAndTheInternetHigh103TopUpBQuestions } from './col-computers-and-the-internetHigh103TopUpB'
import { colConstitution101High103TopUpQuestions } from './col-constitution-101High103TopUp'
import { colEarthScienceHigh103TopUpAQuestions } from './col-earth-scienceHigh103TopUpA'
import { colEarthScienceHigh103TopUpBQuestions } from './col-earth-scienceHigh103TopUpB'
import { colEurekaMathAlgebraIHigh103TopUpAQuestions } from './col-eureka-math-algebra-iHigh103TopUpA'
import { colEurekaMathAlgebraIHigh103TopUpBQuestions } from './col-eureka-math-algebra-iHigh103TopUpB'
import { colEurekaMathAlgebraIiHigh103TopUpAQuestions } from './col-eureka-math-algebra-iiHigh103TopUpA'
import { colEurekaMathAlgebraIiHigh103TopUpBQuestions } from './col-eureka-math-algebra-iiHigh103TopUpB'
import { colEurekaMathGeometryHigh103TopUpAQuestions } from './col-eureka-math-geometryHigh103TopUpA'
import { colEurekaMathGeometryHigh103TopUpBQuestions } from './col-eureka-math-geometryHigh103TopUpB'
import { colFinanceAndCapitalMarketsHigh103TopUpAQuestions } from './col-finance-and-capital-marketsHigh103TopUpA'
import { colFinanceAndCapitalMarketsHigh103TopUpBQuestions } from './col-finance-and-capital-marketsHigh103TopUpB'
import { colGcseMathsUkHigh103TopUpAQuestions } from './col-gcse-maths-ukHigh103TopUpA'
import { colGcseMathsUkHigh103TopUpBQuestions } from './col-gcse-maths-ukHigh103TopUpB'
import { colGetReadyFor7thGradeHigh103TopUpAQuestions } from './col-get-ready-for-7th-gradeHigh103TopUpA'
import { colGetReadyFor7thGradeHigh103TopUpBQuestions } from './col-get-ready-for-7th-gradeHigh103TopUpB'
import { colGetReadyFor8thGradeHigh103TopUpAQuestions } from './col-get-ready-for-8th-gradeHigh103TopUpA'
import { colGetReadyFor8thGradeHigh103TopUpBQuestions } from './col-get-ready-for-8th-gradeHigh103TopUpB'
import { colGetReadyForAlgebra1High103TopUpAQuestions } from './col-get-ready-for-algebra-1High103TopUpA'
import { colGetReadyForAlgebra1High103TopUpBQuestions } from './col-get-ready-for-algebra-1High103TopUpB'
import { colGetReadyForAlgebra2High103TopUpAQuestions } from './col-get-ready-for-algebra-2High103TopUpA'
import { colGetReadyForAlgebra2High103TopUpBQuestions } from './col-get-ready-for-algebra-2High103TopUpB'
import { colGetReadyForApCalculusHigh103TopUpAQuestions } from './col-get-ready-for-ap-calculusHigh103TopUpA'
import { colGetReadyForApCalculusHigh103TopUpBQuestions } from './col-get-ready-for-ap-calculusHigh103TopUpB'
import { colGetReadyForApStatisticsHigh103TopUpAQuestions } from './col-get-ready-for-ap-statisticsHigh103TopUpA'
import { colGetReadyForApStatisticsHigh103TopUpBQuestions } from './col-get-ready-for-ap-statisticsHigh103TopUpB'
import { colGetReadyForGeometryHigh103TopUpAQuestions } from './col-get-ready-for-geometryHigh103TopUpA'
import { colGetReadyForGeometryHigh103TopUpBQuestions } from './col-get-ready-for-geometryHigh103TopUpB'
import { colGetReadyForSatPrepMathHigh103TopUpAQuestions } from './col-get-ready-for-sat-prep-mathHigh103TopUpA'
import { colGetReadyForSatPrepMathHigh103TopUpBQuestions } from './col-get-ready-for-sat-prep-mathHigh103TopUpB'
import { colGetReadyForSatPrepReadingAndWritingHigh103TopUpAQuestions } from './col-get-ready-for-sat-prep-reading-and-writingHigh103TopUpA'
import { colGetReadyForSatPrepReadingAndWritingHigh103TopUpBQuestions } from './col-get-ready-for-sat-prep-reading-and-writingHigh103TopUpB'
import { colGrammarHigh103TopUpAQuestions } from './col-grammarHigh103TopUpA'
import { colGrammarHigh103TopUpBQuestions } from './col-grammarHigh103TopUpB'
import { colHandsOnScienceActivitiesHigh103TopUpAQuestions } from './col-hands-on-science-activitiesHigh103TopUpA'
import { colHandsOnScienceActivitiesHigh103TopUpBQuestions } from './col-hands-on-science-activitiesHigh103TopUpB'
import { colHighSchoolBiologyHigh103TopUpAQuestions } from './col-high-school-biologyHigh103TopUpA'
import { colHighSchoolBiologyHigh103TopUpBQuestions } from './col-high-school-biologyHigh103TopUpB'
import { colHighSchoolChemistryHigh103TopUpAQuestions } from './col-high-school-chemistryHigh103TopUpA'
import { colHighSchoolChemistryHigh103TopUpBQuestions } from './col-high-school-chemistryHigh103TopUpB'
import { colHighSchoolPhysicsHigh103TopUpAQuestions } from './col-high-school-physicsHigh103TopUpA'
import { colHighSchoolPhysicsHigh103TopUpBQuestions } from './col-high-school-physicsHigh103TopUpB'
import { colHscVceMathsAustraliaHigh103TopUpAQuestions } from './col-hsc---vce-maths-australiaHigh103TopUpA'
import { colIntegratedMath1High103TopUpAQuestions } from './col-integrated-math-1High103TopUpA'
import { colIntegratedMath1High103TopUpBQuestions } from './col-integrated-math-1High103TopUpB'
import { colIntegratedMath2High103TopUpAQuestions } from './col-integrated-math-2High103TopUpA'
import { colIntegratedMath2High103TopUpBQuestions } from './col-integrated-math-2High103TopUpB'
import { colIntegratedMath3High103TopUpAQuestions } from './col-integrated-math-3High103TopUpA'
import { colIntegratedMath3High103TopUpBQuestions } from './col-integrated-math-3High103TopUpB'
import { colIntroToCsPythonHigh103TopUpQuestions } from './col-intro-to-cs-pythonHigh103TopUp'
import { colJeeMainPrepIndiaHigh103TopUpAQuestions } from './col-jee-main-prep-indiaHigh103TopUpA'
import { colJeeMainPrepIndiaHigh103TopUpBQuestions } from './col-jee-main-prep-indiaHigh103TopUpB'
import { colMacroeconomicsHigh103TopUpAQuestions } from './col-macroeconomicsHigh103TopUpA'
import { colMacroeconomicsHigh103TopUpBQuestions } from './col-macroeconomicsHigh103TopUpB'
import { colMicroeconomicsHigh103TopUpAQuestions } from './col-microeconomicsHigh103TopUpA'
import { colMicroeconomicsHigh103TopUpBQuestions } from './col-microeconomicsHigh103TopUpB'
import { colMiddleSchoolBigHistoryHigh103TopUpAQuestions } from './col-middle-school-big-historyHigh103TopUpA'
import { colMiddleSchoolBigHistoryHigh103TopUpBQuestions } from './col-middle-school-big-historyHigh103TopUpB'
import { colMiddleSchoolBiologyHigh103TopUpAQuestions } from './col-middle-school-biologyHigh103TopUpA'
import { colMiddleSchoolBiologyHigh103TopUpBQuestions } from './col-middle-school-biologyHigh103TopUpB'
import { colMiddleSchoolChemistryHigh103TopUpAQuestions } from './col-middle-school-chemistryHigh103TopUpA'
import { colMiddleSchoolChemistryHigh103TopUpBQuestions } from './col-middle-school-chemistryHigh103TopUpB'
import { colMiddleSchoolEarthAndSpaceScienceHigh103TopUpAQuestions } from './col-middle-school-earth-and-space-scienceHigh103TopUpA'
import { colMiddleSchoolEarthAndSpaceScienceHigh103TopUpBQuestions } from './col-middle-school-earth-and-space-scienceHigh103TopUpB'
import { colMiddleSchoolPhysicsHigh103TopUpAQuestions } from './col-middle-school-physicsHigh103TopUpA'
import { colMiddleSchoolPhysicsHigh103TopUpBQuestions } from './col-middle-school-physicsHigh103TopUpB'
import { colOerProjectWorldHistoryHigh103TopUpAQuestions } from './col-oer-project-world-historyHigh103TopUpA'
import { colOerProjectWorldHistoryHigh103TopUpBQuestions } from './col-oer-project-world-historyHigh103TopUpB'
import { colPixarInABoxHigh103TopUpAQuestions } from './col-pixar-in-a-boxHigh103TopUpA'
import { colPixarInABoxHigh103TopUpBQuestions } from './col-pixar-in-a-boxHigh103TopUpB'
import { colPracticalPoliticsVotingHigh103TopUpQuestions } from './col-practical-politics-votingHigh103TopUp'
import { colPreAlgebraHigh103TopUpAQuestions } from './col-pre-algebraHigh103TopUpA'
import { colPreAlgebraHigh103TopUpBQuestions } from './col-pre-algebraHigh103TopUpB'
import { colPrecalculusHigh103TopUpAQuestions } from './col-precalculusHigh103TopUpA'
import { colPrecalculusHigh103TopUpBQuestions } from './col-precalculusHigh103TopUpB'
import { colStatisticsProbabilityHigh103TopUpAQuestions } from './col-statistics-probabilityHigh103TopUpA'
import { colStatisticsProbabilityHigh103TopUpBQuestions } from './col-statistics-probabilityHigh103TopUpB'
import { colTrigonometryHigh103TopUpAQuestions } from './col-trigonometryHigh103TopUpA'
import { colTrigonometryHigh103TopUpBQuestions } from './col-trigonometryHigh103TopUpB'
import { colUsGovernmentAndCivicsHigh103TopUpQuestions } from './col-us-government-and-civicsHigh103TopUp'
import { colUsHistoryHigh103TopUpAQuestions } from './col-us-historyHigh103TopUpA'
import { colUsHistoryHigh103TopUpBQuestions } from './col-us-historyHigh103TopUpB'
import { colWorldHistoryHigh103TopUpAQuestions } from './col-world-historyHigh103TopUpA'
import { colWorldHistoryHigh103TopUpBQuestions } from './col-world-historyHigh103TopUpB'
import { gcseMathsHigh103TopUpAQuestions } from './gcseMathsHigh103TopUpA'
import { gcseMathsHigh103TopUpBQuestions } from './gcseMathsHigh103TopUpB'
import { gcseScienceHigh103TopUpAQuestions } from './gcseScienceHigh103TopUpA'
import { gcseScienceHigh103TopUpBQuestions } from './gcseScienceHigh103TopUpB'
import { ib_historyHigh103TopUpAQuestions } from './ib_historyHigh103TopUpA'
import { ib_historyHigh103TopUpBQuestions } from './ib_historyHigh103TopUpB'
import { jeeMainHigh103TopUpAQuestions } from './jeeMainHigh103TopUpA'
import { jeeMainHigh103TopUpBQuestions } from './jeeMainHigh103TopUpB'
import { lifeSkillsHighHigh103TopUpAQuestions } from './lifeSkillsHighHigh103TopUpA'
import { lifeSkillsHighHigh103TopUpBQuestions } from './lifeSkillsHighHigh103TopUpB'
import { mathematics_extensionsHigh103TopUpAQuestions } from './mathematics_extensionsHigh103TopUpA'
import { mathematics_extensionsHigh103TopUpBQuestions } from './mathematics_extensionsHigh103TopUpB'
import { neetPrepHigh103TopUpAQuestions } from './neetPrepHigh103TopUpA'
import { neetPrepHigh103TopUpBQuestions } from './neetPrepHigh103TopUpB'
import { philYear10High103TopUpAQuestions } from './philYear10High103TopUpA'
import { philYear10High103TopUpBQuestions } from './philYear10High103TopUpB'
import { philYear11High103TopUpAQuestions } from './philYear11High103TopUpA'
import { philYear11High103TopUpBQuestions } from './philYear11High103TopUpB'
import { philYear12High103TopUpAQuestions } from './philYear12High103TopUpA'
import { philYear12High103TopUpBQuestions } from './philYear12High103TopUpB'
import { philYear7High103TopUpAQuestions } from './philYear7High103TopUpA'
import { philYear7High103TopUpBQuestions } from './philYear7High103TopUpB'
import { philYear8High103TopUpQuestions } from './philYear8High103TopUp'
import { philYear9High103TopUpQuestions } from './philYear9High103TopUp'
import { politicalPhilosophyHigh103TopUpQuestions } from './politicalPhilosophyHigh103TopUp'
import { practicalPoliticsHigh103TopUpQuestions } from './practicalPoliticsHigh103TopUp'
import { principles_economics_3eHigh103TopUpAQuestions } from './principles_economics_3eHigh103TopUpA'
import { principles_economics_3eHigh103TopUpBQuestions } from './principles_economics_3eHigh103TopUpB'
import { psychology_2eHigh103TopUpAQuestions } from './psychology_2eHigh103TopUpA'
import { psychology_2eHigh103TopUpBQuestions } from './psychology_2eHigh103TopUpB'

const GENERIC_HIGH_103_HINTS = new Set([
  'Before choosing an answer, say out loud what the concept is and what the question wants from you.',
  'Name the relevant rule first, then apply it carefully.',
  'State the definition first, then match the option that fits it.',
  'Name the rule first, then apply it to the exact numbers in the setup.',
  'Translate the question into plain language before evaluating the choices.',
])

function high103MentorHint(question: Question): string {
  const text = `${question.chapter} ${question.title} ${question.prompt}`.toLowerCase()

  if (text.includes('macroeconomic') || text.includes('scarcity') || text.includes('opportunity cost') || text.includes('inflation') || text.includes('gdp') || text.includes('unemployment') || text.includes('monetary') || text.includes('fiscal')) {
    return 'Identify the macro relationship before choosing: scarcity, opportunity cost, aggregate demand/supply, inflation, unemployment, GDP, fiscal policy, or monetary policy. Then ask whether the answer describes a shift, a movement, or a measurement.'
  }
  if (text.includes('microeconomic') || text.includes('supply') || text.includes('demand') || text.includes('elastic') || text.includes('market') || text.includes('marginal') || text.includes('externality')) {
    return 'Draw the market or marginal tradeoff in your head first. Microeconomics questions usually turn on who changes behavior, which curve moves, and whether the decision is made at the margin.'
  }
  if (text.includes('biology') || text.includes('cell') || text.includes('enzyme') || text.includes('protein') || text.includes('genetic') || text.includes('ecosystem')) {
    return 'Name the biological system and the mechanism linking structure to function. Check whether the question is asking about evidence, molecules, cells, inheritance, evolution, or energy flow.'
  }
  if (text.includes('chemistry') || text.includes('molecule') || text.includes('bond') || text.includes('acid') || text.includes('reaction') || text.includes('stoichi')) {
    return 'Track particles and conservation first: atoms, charge, electrons, energy, and moles do not disappear. The right answer should fit both the chemical mechanism and the quantities given.'
  }
  if (text.includes('physics') || text.includes('force') || text.includes('motion') || text.includes('energy') || text.includes('wave') || text.includes('circuit')) {
    return 'Identify the physical quantity being asked for, then choose the law that connects the given variables. A units check can often reveal whether the reasoning is about force, energy, power, momentum, or charge.'
  }
  if (text.includes('climate') || text.includes('earth') || text.includes('geology') || text.includes('weather')) {
    return 'Separate the observation from the process that explains it, and keep timescale in view. Earth science answers usually rely on energy flow, matter cycles, evidence patterns, or system feedbacks.'
  }
  if (text.includes('algebra') || text.includes('equation') || text.includes('inequality') || text.includes('slope') || text.includes('quadratic') || text.includes('function')) {
    return 'Choose the algebra move before calculating: simplify, solve, factor, substitute, or read the graph. Keep signs and operation order visible, because most distractors come from one small reversal.'
  }
  if (text.includes('geometry') || text.includes('angle') || text.includes('triangle') || text.includes('circle') || text.includes('area') || text.includes('volume')) {
    return 'Name the figure property or formula before using numbers. Check whether the question asks for length, angle, area, surface area, or volume so the units and operation match.'
  }
  if (text.includes('statistic') || text.includes('probability') || text.includes('data') || text.includes('sample') || text.includes('mean') || text.includes('median')) {
    return 'Identify the data idea first: center, spread, probability, sampling, correlation, or inference. Then compare the answer to what the statistic can actually claim from the information given.'
  }
  if (text.includes('history') || text.includes('government') || text.includes('civic') || text.includes('constitution') || text.includes('politic')) {
    return 'Place the event, document, or institution in context before choosing. Ask who has authority, what changed, and which evidence in the prompt supports that interpretation.'
  }
  if (text.includes('english') || text.includes('literature') || text.includes('reading') || text.includes('grammar') || text.includes('vocab')) {
    return 'Use the sentence or passage as evidence, not just the answer that sounds polished. For grammar and vocabulary, test how the word or structure functions in context.'
  }
  if (text.includes('computer') || text.includes('program') || text.includes('internet') || text.includes('python') || text.includes('code')) {
    return 'Identify what the system is doing with data, instructions, networks, or user input. The best computing answer should explain the actual behavior, not just repeat a technical term.'
  }
  if (text.includes('finance') || text.includes('capital') || text.includes('credit') || text.includes('interest') || text.includes('budget')) {
    return 'Translate the prompt into the financial relationship being tested: cash flow, risk, return, compounding, credit cost, or market role. Then check whether the answer describes the amount, rate, or institution correctly.'
  }
  if (text.includes('art')) {
    return 'Look for the visual evidence named in the prompt: medium, style, patronage, period, or purpose. Art history answers should connect the feature to context rather than just naming a movement.'
  }

  return 'Identify the course concept and the exact task in the prompt before reading the choices. Eliminate answers that use familiar vocabulary but do not fit the situation described.'
}

function enrichHigh103Hints(questions: Question[]): Question[] {
  return questions.map((question) =>
    GENERIC_HIGH_103_HINTS.has(question.mentorHint)
      ? { ...question, mentorHint: high103MentorHint(question) }
      : question,
  )
}

const RAW_HIGH_103_TOPUPS: Record<string, Question[]> = {
  "alevelBiology": [...alevelBiologyHigh103TopUpAQuestions, ...alevelBiologyHigh103TopUpBQuestions],
  "alevelChemistry": [...alevelChemistryHigh103TopUpAQuestions, ...alevelChemistryHigh103TopUpBQuestions],
  "alevelComputerScience": [...alevelComputerScienceHigh103TopUpAQuestions, ...alevelComputerScienceHigh103TopUpBQuestions],
  "alevelEconomics": [...alevelEconomicsHigh103TopUpAQuestions, ...alevelEconomicsHigh103TopUpBQuestions],
  "alevelEnglish": [...alevelEnglishHigh103TopUpAQuestions, ...alevelEnglishHigh103TopUpBQuestions],
  "alevelPhysics": [...alevelPhysicsHigh103TopUpAQuestions, ...alevelPhysicsHigh103TopUpBQuestions],
  "apEuropeanHistory": apEuropeanHistoryHigh103TopUpQuestions,
  "apPsychology": apPsychologyHigh103TopUpQuestions,
  "biology_2e": [...biology_2eHigh103TopUpAQuestions, ...biology_2eHigh103TopUpBQuestions],
  "col-10th-grade-reading-and-vocab": [...col10thGradeReadingAndVocabHigh103TopUpAQuestions, ...col10thGradeReadingAndVocabHigh103TopUpBQuestions],
  "col-7th-grade-math": [...col7thGradeMathHigh103TopUpAQuestions, ...col7thGradeMathHigh103TopUpBQuestions],
  "col-7th-grade-ny-next-gen": [...col7thGradeNyNextGenHigh103TopUpAQuestions, ...col7thGradeNyNextGenHigh103TopUpBQuestions],
  "col-7th-grade-reading-and-vocab": [...col7thGradeReadingAndVocabHigh103TopUpAQuestions, ...col7thGradeReadingAndVocabHigh103TopUpBQuestions],
  "col-8th-grade-math": [...col8thGradeMathHigh103TopUpAQuestions, ...col8thGradeMathHigh103TopUpBQuestions],
  "col-8th-grade-ny-next-gen": [...col8thGradeNyNextGenHigh103TopUpAQuestions, ...col8thGradeNyNextGenHigh103TopUpBQuestions],
  "col-8th-grade-reading-and-vocab": [...col8thGradeReadingAndVocabHigh103TopUpAQuestions, ...col8thGradeReadingAndVocabHigh103TopUpBQuestions],
  "col-9th-grade-reading-and-vocab": col9thGradeReadingAndVocabHigh103TopUpAQuestions,
  "col-a-level-biology": [...colALevelBiologyHigh103TopUpAQuestions, ...colALevelBiologyHigh103TopUpBQuestions],
  "col-a-level-economics": [...colALevelEconomicsHigh103TopUpAQuestions, ...colALevelEconomicsHigh103TopUpBQuestions],
  "col-a-level-maths": [...colALevelMathsHigh103TopUpAQuestions, ...colALevelMathsHigh103TopUpBQuestions],
  "col-algebra-1-ny-next-gen": [...colAlgebra1NyNextGenHigh103TopUpAQuestions, ...colAlgebra1NyNextGenHigh103TopUpBQuestions],
  "col-algebra-basics": [...colAlgebraBasicsHigh103TopUpAQuestions, ...colAlgebraBasicsHigh103TopUpBQuestions],
  "col-ap-art-history": colApArtHistoryHigh103TopUpQuestions,
  "col-ap-biology": colApBiologyHigh103TopUpQuestions,
  "col-ap-calculus": colApCalculusHigh103TopUpQuestions,
  "col-ap-chemistry": colApChemistryHigh103TopUpQuestions,
  "col-ap-computer-science": colApComputerScienceHigh103TopUpQuestions,
  "col-ap-computer-science-principles": [...colApComputerSciencePrinciplesHigh103TopUpAQuestions, ...colApComputerSciencePrinciplesHigh103TopUpBQuestions],
  "col-ap-economics": colApEconomicsHigh103TopUpQuestions,
  "col-ap-english-literature": colApEnglishLiteratureHigh103TopUpQuestions,
  "col-ap-macroeconomics": [...colApMacroeconomicsHigh103TopUpAQuestions, ...colApMacroeconomicsHigh103TopUpBQuestions],
  "col-ap-microeconomics": [...colApMicroeconomicsHigh103TopUpAQuestions, ...colApMicroeconomicsHigh103TopUpBQuestions],
  "col-ap-physics": colApPhysicsHigh103TopUpQuestions,
  "col-ap-u-s-history": colApUSHistoryHigh103TopUpQuestions,
  "col-ap-us-government-politics": colApUsGovernmentPoliticsHigh103TopUpQuestions,
  "col-ap-us-history": [...colApUsHistoryHigh103TopUpAQuestions, ...colApUsHistoryHigh103TopUpBQuestions],
  "col-ap-world-history": colApWorldHistoryHigh103TopUpQuestions,
  "col-art-history": [...colArtHistoryHigh103TopUpAQuestions, ...colArtHistoryHigh103TopUpBQuestions],
  "col-climate-project": [...colClimateProjectHigh103TopUpAQuestions, ...colClimateProjectHigh103TopUpBQuestions],
  "col-computer-programming": [...colComputerProgrammingHigh103TopUpAQuestions, ...colComputerProgrammingHigh103TopUpBQuestions],
  "col-computer-science-theory": [...colComputerScienceTheoryHigh103TopUpAQuestions, ...colComputerScienceTheoryHigh103TopUpBQuestions],
  "col-computers-and-the-internet": [...colComputersAndTheInternetHigh103TopUpAQuestions, ...colComputersAndTheInternetHigh103TopUpBQuestions],
  "col-constitution-101": colConstitution101High103TopUpQuestions,
  "col-earth-science": [...colEarthScienceHigh103TopUpAQuestions, ...colEarthScienceHigh103TopUpBQuestions],
  "col-eureka-math-algebra-i": [...colEurekaMathAlgebraIHigh103TopUpAQuestions, ...colEurekaMathAlgebraIHigh103TopUpBQuestions],
  "col-eureka-math-algebra-ii": [...colEurekaMathAlgebraIiHigh103TopUpAQuestions, ...colEurekaMathAlgebraIiHigh103TopUpBQuestions],
  "col-eureka-math-geometry": [...colEurekaMathGeometryHigh103TopUpAQuestions, ...colEurekaMathGeometryHigh103TopUpBQuestions],
  "col-finance-and-capital-markets": [...colFinanceAndCapitalMarketsHigh103TopUpAQuestions, ...colFinanceAndCapitalMarketsHigh103TopUpBQuestions],
  "col-gcse-maths-uk": [...colGcseMathsUkHigh103TopUpAQuestions, ...colGcseMathsUkHigh103TopUpBQuestions],
  "col-get-ready-for-7th-grade": [...colGetReadyFor7thGradeHigh103TopUpAQuestions, ...colGetReadyFor7thGradeHigh103TopUpBQuestions],
  "col-get-ready-for-8th-grade": [...colGetReadyFor8thGradeHigh103TopUpAQuestions, ...colGetReadyFor8thGradeHigh103TopUpBQuestions],
  "col-get-ready-for-algebra-1": [...colGetReadyForAlgebra1High103TopUpAQuestions, ...colGetReadyForAlgebra1High103TopUpBQuestions],
  "col-get-ready-for-algebra-2": [...colGetReadyForAlgebra2High103TopUpAQuestions, ...colGetReadyForAlgebra2High103TopUpBQuestions],
  "col-get-ready-for-ap-calculus": [...colGetReadyForApCalculusHigh103TopUpAQuestions, ...colGetReadyForApCalculusHigh103TopUpBQuestions],
  "col-get-ready-for-ap-statistics": [...colGetReadyForApStatisticsHigh103TopUpAQuestions, ...colGetReadyForApStatisticsHigh103TopUpBQuestions],
  "col-get-ready-for-geometry": [...colGetReadyForGeometryHigh103TopUpAQuestions, ...colGetReadyForGeometryHigh103TopUpBQuestions],
  "col-get-ready-for-sat-prep-math": [...colGetReadyForSatPrepMathHigh103TopUpAQuestions, ...colGetReadyForSatPrepMathHigh103TopUpBQuestions],
  "col-get-ready-for-sat-prep-reading-and-writing": [...colGetReadyForSatPrepReadingAndWritingHigh103TopUpAQuestions, ...colGetReadyForSatPrepReadingAndWritingHigh103TopUpBQuestions],
  "col-grammar": [...colGrammarHigh103TopUpAQuestions, ...colGrammarHigh103TopUpBQuestions],
  "col-hands-on-science-activities": [...colHandsOnScienceActivitiesHigh103TopUpAQuestions, ...colHandsOnScienceActivitiesHigh103TopUpBQuestions],
  "col-high-school-biology": [...colHighSchoolBiologyHigh103TopUpAQuestions, ...colHighSchoolBiologyHigh103TopUpBQuestions],
  "col-high-school-chemistry": [...colHighSchoolChemistryHigh103TopUpAQuestions, ...colHighSchoolChemistryHigh103TopUpBQuestions],
  "col-high-school-physics": [...colHighSchoolPhysicsHigh103TopUpAQuestions, ...colHighSchoolPhysicsHigh103TopUpBQuestions],
  "col-hsc---vce-maths-australia": colHscVceMathsAustraliaHigh103TopUpAQuestions,
  "col-integrated-math-1": [...colIntegratedMath1High103TopUpAQuestions, ...colIntegratedMath1High103TopUpBQuestions],
  "col-integrated-math-2": [...colIntegratedMath2High103TopUpAQuestions, ...colIntegratedMath2High103TopUpBQuestions],
  "col-integrated-math-3": [...colIntegratedMath3High103TopUpAQuestions, ...colIntegratedMath3High103TopUpBQuestions],
  "col-intro-to-cs-python": colIntroToCsPythonHigh103TopUpQuestions,
  "col-jee-main-prep-india": [...colJeeMainPrepIndiaHigh103TopUpAQuestions, ...colJeeMainPrepIndiaHigh103TopUpBQuestions],
  "col-macroeconomics": [...colMacroeconomicsHigh103TopUpAQuestions, ...colMacroeconomicsHigh103TopUpBQuestions],
  "col-microeconomics": [...colMicroeconomicsHigh103TopUpAQuestions, ...colMicroeconomicsHigh103TopUpBQuestions],
  "col-middle-school-big-history": [...colMiddleSchoolBigHistoryHigh103TopUpAQuestions, ...colMiddleSchoolBigHistoryHigh103TopUpBQuestions],
  "col-middle-school-biology": [...colMiddleSchoolBiologyHigh103TopUpAQuestions, ...colMiddleSchoolBiologyHigh103TopUpBQuestions],
  "col-middle-school-chemistry": [...colMiddleSchoolChemistryHigh103TopUpAQuestions, ...colMiddleSchoolChemistryHigh103TopUpBQuestions],
  "col-middle-school-earth-and-space-science": [...colMiddleSchoolEarthAndSpaceScienceHigh103TopUpAQuestions, ...colMiddleSchoolEarthAndSpaceScienceHigh103TopUpBQuestions],
  "col-middle-school-physics": [...colMiddleSchoolPhysicsHigh103TopUpAQuestions, ...colMiddleSchoolPhysicsHigh103TopUpBQuestions],
  "col-oer-project-world-history": [...colOerProjectWorldHistoryHigh103TopUpAQuestions, ...colOerProjectWorldHistoryHigh103TopUpBQuestions],
  "col-pixar-in-a-box": [...colPixarInABoxHigh103TopUpAQuestions, ...colPixarInABoxHigh103TopUpBQuestions],
  "col-practical-politics-voting": colPracticalPoliticsVotingHigh103TopUpQuestions,
  "col-pre-algebra": [...colPreAlgebraHigh103TopUpAQuestions, ...colPreAlgebraHigh103TopUpBQuestions],
  "col-precalculus": [...colPrecalculusHigh103TopUpAQuestions, ...colPrecalculusHigh103TopUpBQuestions],
  "col-statistics-probability": [...colStatisticsProbabilityHigh103TopUpAQuestions, ...colStatisticsProbabilityHigh103TopUpBQuestions],
  "col-trigonometry": [...colTrigonometryHigh103TopUpAQuestions, ...colTrigonometryHigh103TopUpBQuestions],
  "col-us-government-and-civics": colUsGovernmentAndCivicsHigh103TopUpQuestions,
  "col-us-history": [...colUsHistoryHigh103TopUpAQuestions, ...colUsHistoryHigh103TopUpBQuestions],
  "col-world-history": [...colWorldHistoryHigh103TopUpAQuestions, ...colWorldHistoryHigh103TopUpBQuestions],
  "gcseMaths": [...gcseMathsHigh103TopUpAQuestions, ...gcseMathsHigh103TopUpBQuestions],
  "gcseScience": [...gcseScienceHigh103TopUpAQuestions, ...gcseScienceHigh103TopUpBQuestions],
  "ib_history": [...ib_historyHigh103TopUpAQuestions, ...ib_historyHigh103TopUpBQuestions],
  "jeeMain": [...jeeMainHigh103TopUpAQuestions, ...jeeMainHigh103TopUpBQuestions],
  "lifeSkillsHigh": [...lifeSkillsHighHigh103TopUpAQuestions, ...lifeSkillsHighHigh103TopUpBQuestions],
  "mathematics_extensions": [...mathematics_extensionsHigh103TopUpAQuestions, ...mathematics_extensionsHigh103TopUpBQuestions],
  "neetPrep": [...neetPrepHigh103TopUpAQuestions, ...neetPrepHigh103TopUpBQuestions],
  "philYear10": [...philYear10High103TopUpAQuestions, ...philYear10High103TopUpBQuestions],
  "philYear11": [...philYear11High103TopUpAQuestions, ...philYear11High103TopUpBQuestions],
  "philYear12": [...philYear12High103TopUpAQuestions, ...philYear12High103TopUpBQuestions],
  "philYear7": [...philYear7High103TopUpAQuestions, ...philYear7High103TopUpBQuestions],
  "philYear8": philYear8High103TopUpQuestions,
  "philYear9": philYear9High103TopUpQuestions,
  "politicalPhilosophy": politicalPhilosophyHigh103TopUpQuestions,
  "practicalPolitics": practicalPoliticsHigh103TopUpQuestions,
  "principles_economics_3e": [...principles_economics_3eHigh103TopUpAQuestions, ...principles_economics_3eHigh103TopUpBQuestions],
  "psychology_2e": [...psychology_2eHigh103TopUpAQuestions, ...psychology_2eHigh103TopUpBQuestions],
}

export const HIGH_103_TOPUPS: Record<string, Question[]> = Object.fromEntries(
  Object.entries(RAW_HIGH_103_TOPUPS).map(([trackId, questions]) => [trackId, enrichHigh103Hints(questions)]),
)
