import { makeQuestionBank } from './base'

// Generated by scripts/build_opentrivia_apworld_final_two_import.cjs.
// Manual allowlist: the last two clean AP World rows from the source report.

export const openTriviaWorldHistoryFinalTwoQuestions = makeQuestionBank('AP', [
  {
    id: 369101,
    chapter: "Early Modern Europe",
    source: 'OpenTriviaQA',
    title: "Salem Witch Trials",
    prompt: "Which of the following events happened on March,1692?",
    correct: "The Salem witch trials began in New England",
    wrong: [["An earthquake in Mexico killed over 10,000","This answer belongs to a different historical event or period.","Match the named clue in the prompt to the specific world-history fact being tested."],["General Braddock was killed by the French","This answer belongs to a different historical event or period.","Match the named clue in the prompt to the specific world-history fact being tested."],["The Indians sold Manhattan Island to the Dutch","This answer belongs to a different historical event or period.","Match the named clue in the prompt to the specific world-history fact being tested."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::history::158). Included in the AP World History final two-question micro-batch.",
  },
  {
    id: 369102,
    chapter: "Global Turning Points",
    source: 'OpenTriviaQA',
    title: "Balloon Parachute",
    prompt: "According to some theories, the parachute was invented in 1783 by Sebastien Lenormand in France. Two years later, Jean-Pierre Blanchard demonstrated it as a means of safely getting down on earth from this.",
    correct: "Balloon",
    wrong: [["Tree","This answer belongs to a different historical event or period.","Match the named clue in the prompt to the specific world-history fact being tested."],["Cliff","This answer belongs to a different historical event or period.","Match the named clue in the prompt to the specific world-history fact being tested."],["Building","This answer belongs to a different historical event or period.","Match the named clue in the prompt to the specific world-history fact being tested."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::history::240). Included in the AP World History final two-question micro-batch.",
  },
])
