import { makeQuestionBank } from './base'
import { polish as runPolish } from './polishPipeline'
import {
  OPEN_TRIVIA_WAVE20_SUB_TOPICS,
  OPEN_TRIVIA_WAVE20_MENTOR_HINTS,
  OPEN_TRIVIA_WAVE20_CORRECT_SHORTENED,
} from './openTriviaWave20Polish'

// Generated by scripts/build_opentrivia_apcs_extension_import.cjs.
// Manual allowlist: durable AP Computer Science concept/history rows only.

const _baseOpenTriviaApcsExtensionQuestions = makeQuestionBank('AP', [
  {
    id: 360001,
    chapter: "Computer Systems and the Web",
    source: 'OpenTriviaQA',
    title: "Web Cookies",
    prompt: "In Internet parlance, what is a cookie?",
    correct: "Something stored on the client computer by a web page's program",
    wrong: [["Something tasty on a web page","This follows the everyday meaning of cookie, but Internet cookies are data records saved by a site in the user's browser.","Look for the browser-storage meaning: a cookie is small client-side state that can be sent back to the site later."],["Something made up (or cooked) on a web page","This sounds like page content generated by a server or script. A web cookie is instead stored on the client computer between visits or requests.","Separate generated page content from stored browser state."],["A portion of a program governing a web page","That describes code or a script controlling page behavior. A cookie is not program logic; it is stored data associated with a site.","Ask whether the item is executable code or data saved by the browser."]],
    lesson: "Computer-system questions usually ask what role a tool plays: input, output, storage, or web state. A cookie is saved by a site on the client side; a speaker is output because it produces sound.",
  },
  {
    id: 360002,
    chapter: "Computer Systems and the Web",
    source: 'OpenTriviaQA',
    title: "Output Devices",
    prompt: "Which output device produces audible sound rather than printed pages or visual display?",
    correct: "Speaker",
    wrong: [["A printer for paper output","A printer is an output device, but its medium is paper. The question asks for audible output, which points to a speaker.","Match the output medium: sound, paper, and visual display are different device roles."],["A microphone for audio input","A microphone handles sound, but it captures audio as input. A speaker sends audio out to the user.","Check the direction of information flow: microphone in, speaker out."],["A monitor for visual output","A monitor is output, but it displays images or text rather than producing audible sound.","Use both clues together: output device plus audible sound."]],
    lesson: "Computer-system questions usually ask what role a tool plays: input, output, storage, or web state. A cookie is saved by a site on the client side; a speaker is output because it produces sound.",
  },
  {
    id: 360003,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Logic Programming",
    prompt: "Which programming language is based on Horn clauses?",
    correct: "Prolog",
    wrong: [["Erlang","Erlang is associated with concurrent and fault-tolerant systems, not the Horn-clause logic-programming tradition named in the clue.","Horn clauses are the giveaway for logic programming, especially Prolog."],["Lisp","Lisp is historically important for symbolic processing and list structures, but Horn clauses point to Prolog's logic-programming model.","Connect the clue to the programming paradigm: Horn clauses belong with Prolog."],["PL/I","PL/I was a general-purpose imperative language, not the language built around Horn-clause inference.","If the clue mentions clauses and inference, think Prolog rather than procedural languages."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360004,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "The C Programming Language",
    prompt: "The fundamental book The C Programming Language was written in 1978 by Brian Kernighan and what other computer scientist?",
    correct: "Dennis Ritchie",
    wrong: [["DRM","DRM is just a set of initials, not Kernighan's coauthor. The C book is commonly tied to Kernighan and Ritchie.","For the classic C text, remember the K&R pairing: Kernighan plus Dennis Ritchie."],["MDR","MDR rearranges initials but does not name the Bell Labs computer scientist who co-wrote the book.","Use the author clue, not the letters: Ritchie is the coauthor and creator of C."],["RMD","RMD is not a person's name in this context. The title points to Dennis Ritchie, the R in K&R.","The historical anchor is K&R: Brian Kernighan and Dennis Ritchie."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360005,
    chapter: "Data Representation",
    source: 'OpenTriviaQA',
    title: "Terabits",
    prompt: "How many bits are in one terabit?",
    correct: "1,000,000,000,000",
    wrong: [["1,000","1,000 is the scale for kilo, not tera. A terabit uses the trillion-scale prefix in this decimal unit clue.","Compare the SI prefixes first: kilo is thousand, tera is trillion."],["10","10 confuses the prefix with a single power base. Tera means 10^12, which expands to 1,000,000,000,000 bits.","Translate the prefix into an exponent before choosing a numeral."],["8","8 is the bit count in one byte, not the number of bits in a terabit.","Do not switch units: this asks for bits in a terabit, not bits in a byte."]],
    lesson: "Data-size questions are place-value questions in computer clothing. A terabit is one trillion bits, so do the prefix scale first before worrying about bytes or devices.",
  },
  {
    id: 360006,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Fortran",
    prompt: "Which was the first implemented high-level general purpose programming language?",
    correct: "Fortran",
    wrong: [["Cobol","COBOL was influential for business data processing, but it came after Fortran's early implementation for scientific computing.","Use the chronology clue: Fortran is the early implemented high-level general-purpose language."],["BASIC","BASIC made programming more accessible in education, but it arrived years after Fortran.","First implemented high-level language points to IBM's Fortran era, not later teaching languages."],["Pascal","Pascal is a later structured programming language, so it does not fit the 'first implemented' clue.","When the prompt asks for earliest implementation, compare timelines before matching familiar names."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360007,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Ada",
    prompt: "Which name is also the name of a computer programming language?",
    correct: "Ada",
    wrong: [["Amelia","Amelia is a given name, but it is not the well-known programming language name in this clue.","Look for the name that is also a language, named in honor of Ada Lovelace."],["Anna","Anna fits the pattern of a person's name, but it is not the established programming language answer here.","The computing-history clue is Ada, connected to Ada Lovelace."],["Agnes","Agnes is another name distractor; the programming language in the choices is Ada.","Among ordinary names, choose the one with a language and computing-history connection."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360008,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "C",
    prompt: "Which letter of the alphabet is also the name of a popular computer programming language?",
    correct: "C",
    wrong: [["E","E has been used as a language name in niche contexts, but the common single-letter programming language expected by this clue is C.","For single-letter language trivia, choose the widely taught and widely used language."],["B","B was a predecessor to C, but the prompt asks for the popular language name. C is the durable mainstream answer.","Watch for predecessor distractors: B influenced C, but C is the popular language."],["A","A is a letter, but it is not the standard popular programming language answer to this clue.","Use the popularity clue, not just the fact that the option is a letter."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360009,
    chapter: "Algorithms and Optimization",
    source: 'OpenTriviaQA',
    title: "Linear Programming",
    prompt: "The subject that studies the solution of a system of linear inequalities is called Linear Programming. Which of these men was most instrumental in its development?",
    correct: "George B. Dantzig",
    wrong: [["Sir Isaac Barrow","Barrow was a 17th-century mathematician, far earlier than the modern optimization field of linear programming.","Use the modern optimization clue rather than choosing an early calculus-era mathematician."],["Sir Isaac Newton","Newton is central to physics and calculus, but he is not the linear-programming figure associated with the simplex method tradition.","Linear programming points to optimization history, not general mathematical fame."],["Alfred Whitehead","Whitehead is known for logic and philosophy of mathematics, not for developing linear programming as an optimization method.","Match the named field to its developer: linear programming is tied to George Dantzig."]],
    lesson: "Linear programming is an optimization method for systems of linear constraints. The historical clue points to George Dantzig, whose simplex method made the field practical.",
  },
])

export const openTriviaApcsExtensionQuestions = runPolish(_baseOpenTriviaApcsExtensionQuestions, [
  {
    subTopics: OPEN_TRIVIA_WAVE20_SUB_TOPICS,
    mentorHints: OPEN_TRIVIA_WAVE20_MENTOR_HINTS,
    correctShortened: OPEN_TRIVIA_WAVE20_CORRECT_SHORTENED,
    source: 'openTriviaWave20',
  },
])
