import { makeQuestionBank } from './base'
import { polish as runPolish } from './polishPipeline'
import {
  OPEN_TRIVIA_WAVE20_SUB_TOPICS,
  OPEN_TRIVIA_WAVE20_MENTOR_HINTS,
  OPEN_TRIVIA_WAVE20_CORRECT_SHORTENED,
} from './openTriviaWave20Polish'

// Generated by scripts/build_opentrivia_apcs_extension_import.cjs.
// Manual allowlist: durable AP Computer Science concept/history rows only.

const _baseOpenTriviaApcsExtensionQuestions = makeQuestionBank('AP', [
  {
    id: 360001,
    chapter: "Computer Systems and the Web",
    source: 'OpenTriviaQA',
    title: "Web Cookies",
    prompt: "In Internet parlance, what is a cookie?",
    correct: "Something stored on the client computer by a web page's program",
    wrong: [["Something tasty on a web page","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Something made up (or cooked) on a web page","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["A portion of a program governing a web page","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::380). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360002,
    chapter: "Computer Systems and the Web",
    source: 'OpenTriviaQA',
    title: "Output Devices",
    prompt: "Which of these is an output device that produces audible sound?",
    correct: "Speaker",
    wrong: [["Printer","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Microphone","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Monitor","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::1001). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360003,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Logic Programming",
    prompt: "Which programming language is based on Horn clauses?",
    correct: "Prolog",
    wrong: [["Erlang","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Lisp","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["PL/I","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::1054). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360004,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "The C Programming Language",
    prompt: "The fundamental book The C Programming Language was written in 1978 by Brian Kernighan and what other computer scientist?",
    correct: "Dennis Ritchie",
    wrong: [["DRM","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["MDR","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["RMD","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::1057). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360005,
    chapter: "Data Representation",
    source: 'OpenTriviaQA',
    title: "Terabits",
    prompt: "How many bits are in one terabit?",
    correct: "1,000,000,000,000",
    wrong: [["1,000","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["10","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["8","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::1296). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360006,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Fortran",
    prompt: "Which was the first implemented high-level general purpose programming language?",
    correct: "Fortran",
    wrong: [["Cobol","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["BASIC","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Pascal","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::1369). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360007,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Ada",
    prompt: "Which name is also the name of a computer programming language?",
    correct: "Ada",
    wrong: [["Amelia","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Anna","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Agnes","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::2160). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360008,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "C",
    prompt: "Which letter of the alphabet is also the name of a popular computer programming language?",
    correct: "C",
    wrong: [["E","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["B","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["A","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::2167). Included in the reviewed AP Computer Science extension micro-batch.",
  },
  {
    id: 360009,
    chapter: "Algorithms and Optimization",
    source: 'OpenTriviaQA',
    title: "Linear Programming",
    prompt: "The subject that studies the solution of a system of linear inequalities is called Linear Programming. Which of these men was most instrumental in its development?",
    correct: "George B. Dantzig",
    wrong: [["Sir Isaac Barrow","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Sir Isaac Newton","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."],["Alfred Whitehead","This option does not match the computing concept or programming-history clue in the prompt.","Identify whether the question is about web state, devices, programming languages, units, or algorithms."]],
    lesson: "Source: OpenTriviaQA (opentriviaqa::science-technology::2342). Included in the reviewed AP Computer Science extension micro-batch.",
  },
])

export const openTriviaApcsExtensionQuestions = runPolish(_baseOpenTriviaApcsExtensionQuestions, [
  {
    subTopics: OPEN_TRIVIA_WAVE20_SUB_TOPICS,
    mentorHints: OPEN_TRIVIA_WAVE20_MENTOR_HINTS,
    correctShortened: OPEN_TRIVIA_WAVE20_CORRECT_SHORTENED,
    source: 'openTriviaWave20',
  },
])
