import { makeQuestionBank } from './base'
import { polish as runPolish } from './polishPipeline'
import {
  OPEN_TRIVIA_WAVE20_SUB_TOPICS,
  OPEN_TRIVIA_WAVE20_MENTOR_HINTS,
  OPEN_TRIVIA_WAVE20_CORRECT_SHORTENED,
} from './openTriviaWave20Polish'

// Generated by scripts/build_opentrivia_apcs_extension_import.cjs.
// Manual allowlist: durable AP Computer Science concept/history rows only.

const _baseOpenTriviaApcsExtensionQuestions = makeQuestionBank('AP', [
  {
    id: 360001,
    chapter: "Computer Systems and the Web",
    source: 'OpenTriviaQA',
    title: "Web Cookies",
    prompt: "In Internet parlance, what is a cookie?",
    correct: "Something stored on the client computer by a web page's program",
    wrong: [["Something tasty on a web page","Something tasty on a web page is a computing-related answer, but the prompt is asking for Something stored on the client computer by a web page's program: a small bit of client-side state saved by a web page.","Ask whether the clue is about input, output, stored web state, or how a device/program is used."],["Something made up (or cooked) on a web page","Something made up (or cooked) on a web page is a computing-related answer, but the prompt is asking for Something stored on the client computer by a web page's program: a small bit of client-side state saved by a web page.","Ask whether the clue is about input, output, stored web state, or how a device/program is used."],["A portion of a program governing a web page","A portion of a program governing a web page is a computing-related answer, but the prompt is asking for Something stored on the client computer by a web page's program: a small bit of client-side state saved by a web page.","Ask whether the clue is about input, output, stored web state, or how a device/program is used."]],
    lesson: "Computer-system questions usually ask what role a tool plays: input, output, storage, or web state. A cookie is saved by a site on the client side; a speaker is output because it produces sound.",
  },
  {
    id: 360002,
    chapter: "Computer Systems and the Web",
    source: 'OpenTriviaQA',
    title: "Output Devices",
    prompt: "Which output device produces audible sound rather than printed pages or visual display?",
    correct: "Speaker",
    wrong: [["A printer for paper output","A printer for paper output is a computing-related answer, but the prompt is asking for Speaker: an output device that turns digital audio into sound.","Ask whether the clue is about input, output, stored web state, or how a device/program is used."],["A microphone for audio input","A microphone for audio input is a computing-related answer, but the prompt is asking for Speaker: an output device that turns digital audio into sound.","Ask whether the clue is about input, output, stored web state, or how a device/program is used."],["A monitor for visual output","A monitor for visual output is a computing-related answer, but the prompt is asking for Speaker: an output device that turns digital audio into sound.","Ask whether the clue is about input, output, stored web state, or how a device/program is used."]],
    lesson: "Computer-system questions usually ask what role a tool plays: input, output, storage, or web state. A cookie is saved by a site on the client side; a speaker is output because it produces sound.",
  },
  {
    id: 360003,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Logic Programming",
    prompt: "Which programming language is based on Horn clauses?",
    correct: "Prolog",
    wrong: [["Erlang","Erlang is near the programming-language world, but this clue points to Prolog, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["Lisp","Lisp is near the programming-language world, but this clue points to Prolog, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["PL/I","PL/I is near the programming-language world, but this clue points to Prolog, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360004,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "The C Programming Language",
    prompt: "The fundamental book The C Programming Language was written in 1978 by Brian Kernighan and what other computer scientist?",
    correct: "Dennis Ritchie",
    wrong: [["DRM","DRM is near the programming-language world, but this clue points to Dennis Ritchie, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["MDR","MDR is near the programming-language world, but this clue points to Dennis Ritchie, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["RMD","RMD is near the programming-language world, but this clue points to Dennis Ritchie, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360005,
    chapter: "Data Representation",
    source: 'OpenTriviaQA',
    title: "Terabits",
    prompt: "How many bits are in one terabit?",
    correct: "1,000,000,000,000",
    wrong: [["1,000","1,000 misses the scale: tera means a trillion in this AP CS-style unit clue.","For bits and storage prefixes, check the magnitude before picking a familiar smaller number."],["10","10 misses the scale: tera means a trillion in this AP CS-style unit clue.","For bits and storage prefixes, check the magnitude before picking a familiar smaller number."],["8","8 misses the scale: tera means a trillion in this AP CS-style unit clue.","For bits and storage prefixes, check the magnitude before picking a familiar smaller number."]],
    lesson: "Data-size questions are place-value questions in computer clothing. A terabit is one trillion bits, so do the prefix scale first before worrying about bytes or devices.",
  },
  {
    id: 360006,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Fortran",
    prompt: "Which was the first implemented high-level general purpose programming language?",
    correct: "Fortran",
    wrong: [["Cobol","Cobol is near the programming-language world, but this clue points to Fortran, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["BASIC","BASIC is near the programming-language world, but this clue points to Fortran, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["Pascal","Pascal is near the programming-language world, but this clue points to Fortran, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360007,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "Ada",
    prompt: "Which name is also the name of a computer programming language?",
    correct: "Ada",
    wrong: [["Amelia","Amelia is near the programming-language world, but this clue points to Ada, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["Anna","Anna is near the programming-language world, but this clue points to Ada, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["Agnes","Agnes is near the programming-language world, but this clue points to Ada, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360008,
    chapter: "Programming Languages",
    source: 'OpenTriviaQA',
    title: "C",
    prompt: "Which letter of the alphabet is also the name of a popular computer programming language?",
    correct: "C",
    wrong: [["E","E is near the programming-language world, but this clue points to C, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["B","B is near the programming-language world, but this clue points to C, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."],["A","A is near the programming-language world, but this clue points to C, not that language or name.","Use the historical clue, language feature, or exact naming clue before choosing."]],
    lesson: "Programming-language history questions hinge on the exact clue: a language paradigm, the people behind a language, or a name shared with a language. Nearby languages can be plausible without matching that clue.",
  },
  {
    id: 360009,
    chapter: "Algorithms and Optimization",
    source: 'OpenTriviaQA',
    title: "Linear Programming",
    prompt: "The subject that studies the solution of a system of linear inequalities is called Linear Programming. Which of these men was most instrumental in its development?",
    correct: "George B. Dantzig",
    wrong: [["Sir Isaac Barrow","Sir Isaac Barrow is a famous thinker, but not the optimization figure tied to linear programming here.","Match the person to the algorithm or method named in the prompt, not just to mathematics generally."],["Sir Isaac Newton","Sir Isaac Newton is a famous thinker, but not the optimization figure tied to linear programming here.","Match the person to the algorithm or method named in the prompt, not just to mathematics generally."],["Alfred Whitehead","Alfred Whitehead is a famous thinker, but not the optimization figure tied to linear programming here.","Match the person to the algorithm or method named in the prompt, not just to mathematics generally."]],
    lesson: "Linear programming is an optimization method for systems of linear constraints. The historical clue points to George Dantzig, whose simplex method made the field practical.",
  },
])

export const openTriviaApcsExtensionQuestions = runPolish(_baseOpenTriviaApcsExtensionQuestions, [
  {
    subTopics: OPEN_TRIVIA_WAVE20_SUB_TOPICS,
    mentorHints: OPEN_TRIVIA_WAVE20_MENTOR_HINTS,
    correctShortened: OPEN_TRIVIA_WAVE20_CORRECT_SHORTENED,
    source: 'openTriviaWave20',
  },
])
