// Auto-generated by _gen_prim103_aggregator.cjs — primary 103-pass top-ups.
// Merged into the primary catalog by loadQuestionCatalog (appended to matching trackId).
import type { Question } from './types'
import { arithmeticPrim103TopUpQuestions } from './arithmeticPrim103TopUp'
import { basicGeometryPrim103TopUpAQuestions } from './basicGeometryPrim103TopUpA'
import { basicGeometryPrim103TopUpBQuestions } from './basicGeometryPrim103TopUpB'
import { bugsPrimaryPrim103TopUpQuestions } from './bugsPrimaryPrim103TopUp'
import { class1MathPrim103TopUpQuestions } from './class1MathPrim103TopUp'
import { class2MathPrim103TopUpQuestions } from './class2MathPrim103TopUp'
import { class3MathPrim103TopUpQuestions } from './class3MathPrim103TopUp'
import { class4MathPrim103TopUpQuestions } from './class4MathPrim103TopUp'
import { class5MathPrim103TopUpQuestions } from './class5MathPrim103TopUp'
import { class6MathPrim103TopUpQuestions } from './class6MathPrim103TopUp'
import { codingBasicsPrim103TopUpQuestions } from './codingBasicsPrim103TopUp'
import { col3rdGradeMathPrim103TopUpQuestions } from './col-3rd-grade-mathPrim103TopUp'
import { col3rdGradeNyNextGenPrim103TopUpQuestions } from './col-3rd-grade-ny-next-genPrim103TopUp'
import { col3rdGradePrim103TopUpQuestions } from './col-3rd-gradePrim103TopUp'
import { col4thGradeMathPrim103TopUpQuestions } from './col-4th-grade-mathPrim103TopUp'
import { col4thGradeNyNextGenPrim103TopUpQuestions } from './col-4th-grade-ny-next-genPrim103TopUp'
import { col4thGradeReadingAndVocabPrim103TopUpQuestions } from './col-4th-grade-reading-and-vocabPrim103TopUp'
import { col5thGradeMathPrim103TopUpQuestions } from './col-5th-grade-mathPrim103TopUp'
import { col5thGradeNyNextGenPrim103TopUpQuestions } from './col-5th-grade-ny-next-genPrim103TopUp'
import { col5thGradeReadingAndVocabPrim103TopUpQuestions } from './col-5th-grade-reading-and-vocabPrim103TopUp'
import { col6thGradeMathPrim103TopUpQuestions } from './col-6th-grade-mathPrim103TopUp'
import { col6thGradeNyNextGenPrim103TopUpQuestions } from './col-6th-grade-ny-next-genPrim103TopUp'
import { col6thGradeReadingAndVocabPrim103TopUpQuestions } from './col-6th-grade-reading-and-vocabPrim103TopUp'
import { colArithmeticPrim103TopUpQuestions } from './col-arithmeticPrim103TopUp'
import { colBasicGeometryAndMeasurementPrim103TopUpQuestions } from './col-basic-geometry-and-measurementPrim103TopUp'
import { colCodingBasicsPrim103TopUpQuestions } from './col-coding-basicsPrim103TopUp'
import { colEarlyMathReviewPrim103TopUpQuestions } from './col-early-math-reviewPrim103TopUp'
import { colEurekaMath3rd8thGradePrim103TopUpQuestions } from './col-eureka-math-3rd-8th-gradePrim103TopUp'
import { colEurekaMathFoundations3rd8thGradePrim103TopUpQuestions } from './col-eureka-math-foundations-3rd-8th-gradePrim103TopUp'
import { colGetReadyFor3rdGradePrim103TopUpQuestions } from './col-get-ready-for-3rd-gradePrim103TopUp'
import { colGetReadyFor4thGradePrim103TopUpQuestions } from './col-get-ready-for-4th-gradePrim103TopUp'
import { colGetReadyFor5thGradePrim103TopUpQuestions } from './col-get-ready-for-5th-gradePrim103TopUp'
import { colGetReadyFor6thGradePrim103TopUpQuestions } from './col-get-ready-for-6th-gradePrim103TopUp'
import { colTimesTablesPrim103TopUpQuestions } from './col-times-tablesPrim103TopUp'
import { colWordBuildersPrim103TopUpQuestions } from './col-word-buildersPrim103TopUp'
import { dinosPrimaryPrim103TopUpQuestions } from './dinosPrimaryPrim103TopUp'
import { elevenPlusPrim103TopUpQuestions } from './elevenPlusPrim103TopUp'
import { moneyBasicsPrim103TopUpAQuestions } from './moneyBasicsPrim103TopUpA'
import { moneyBasicsPrim103TopUpBQuestions } from './moneyBasicsPrim103TopUpB'
import { naplanYear3Prim103TopUpQuestions } from './naplanYear3Prim103TopUp'
import { naplanYear5Prim103TopUpQuestions } from './naplanYear5Prim103TopUp'
import { oceanPrimaryPrim103TopUpQuestions } from './oceanPrimaryPrim103TopUp'
import { philosophyYear1Prim103TopUpQuestions } from './philosophyYear1Prim103TopUp'
import { philosophyYear2Prim103TopUpQuestions } from './philosophyYear2Prim103TopUp'
import { philosophyYear3Prim103TopUpQuestions } from './philosophyYear3Prim103TopUp'
import { philosophyYear4Prim103TopUpQuestions } from './philosophyYear4Prim103TopUp'
import { philosophyYear5Prim103TopUpQuestions } from './philosophyYear5Prim103TopUp'
import { philosophyYear6Prim103TopUpQuestions } from './philosophyYear6Prim103TopUp'
import { planetsPrimaryPrim103TopUpQuestions } from './planetsPrimaryPrim103TopUp'
import { primaryPrim103TopUpAQuestions } from './primaryPrim103TopUpA'
import { primaryPrim103TopUpBQuestions } from './primaryPrim103TopUpB'
import { pslePrepPrim103TopUpQuestions } from './pslePrepPrim103TopUp'
import { readingVocab4thPrim103TopUpAQuestions } from './readingVocab4thPrim103TopUpA'
import { readingVocab4thPrim103TopUpBQuestions } from './readingVocab4thPrim103TopUpB'
import { readingVocab5thPrim103TopUpAQuestions } from './readingVocab5thPrim103TopUpA'
import { readingVocab5thPrim103TopUpBQuestions } from './readingVocab5thPrim103TopUpB'
import { scienceYear1Prim103TopUpQuestions } from './scienceYear1Prim103TopUp'
import { scienceYear2Prim103TopUpQuestions } from './scienceYear2Prim103TopUp'
import { scienceYear3Prim103TopUpQuestions } from './scienceYear3Prim103TopUp'
import { scienceYear4Prim103TopUpQuestions } from './scienceYear4Prim103TopUp'
import { scienceYear5Prim103TopUpQuestions } from './scienceYear5Prim103TopUp'
import { scienceYear6Prim103TopUpQuestions } from './scienceYear6Prim103TopUp'
import { timesTablesPrim103TopUpQuestions } from './timesTablesPrim103TopUp'
import { wordBuildersPrim103TopUpQuestions } from './wordBuildersPrim103TopUp'

export const PRIMARY_103_TOPUPS: Record<string, Question[]> = {
  "arithmetic": arithmeticPrim103TopUpQuestions,
  "basicGeometry": [...basicGeometryPrim103TopUpAQuestions, ...basicGeometryPrim103TopUpBQuestions],
  "bugsPrimary": bugsPrimaryPrim103TopUpQuestions,
  "class1Math": class1MathPrim103TopUpQuestions,
  "class2Math": class2MathPrim103TopUpQuestions,
  "class3Math": class3MathPrim103TopUpQuestions,
  "class4Math": class4MathPrim103TopUpQuestions,
  "class5Math": class5MathPrim103TopUpQuestions,
  "class6Math": class6MathPrim103TopUpQuestions,
  "codingBasics": codingBasicsPrim103TopUpQuestions,
  "col-3rd-grade": col3rdGradePrim103TopUpQuestions,
  "col-3rd-grade-math": col3rdGradeMathPrim103TopUpQuestions,
  "col-3rd-grade-ny-next-gen": col3rdGradeNyNextGenPrim103TopUpQuestions,
  "col-4th-grade-math": col4thGradeMathPrim103TopUpQuestions,
  "col-4th-grade-ny-next-gen": col4thGradeNyNextGenPrim103TopUpQuestions,
  "col-4th-grade-reading-and-vocab": col4thGradeReadingAndVocabPrim103TopUpQuestions,
  "col-5th-grade-math": col5thGradeMathPrim103TopUpQuestions,
  "col-5th-grade-ny-next-gen": col5thGradeNyNextGenPrim103TopUpQuestions,
  "col-5th-grade-reading-and-vocab": col5thGradeReadingAndVocabPrim103TopUpQuestions,
  "col-6th-grade-math": col6thGradeMathPrim103TopUpQuestions,
  "col-6th-grade-ny-next-gen": col6thGradeNyNextGenPrim103TopUpQuestions,
  "col-6th-grade-reading-and-vocab": col6thGradeReadingAndVocabPrim103TopUpQuestions,
  "col-arithmetic": colArithmeticPrim103TopUpQuestions,
  "col-basic-geometry-and-measurement": colBasicGeometryAndMeasurementPrim103TopUpQuestions,
  "col-coding-basics": colCodingBasicsPrim103TopUpQuestions,
  "col-early-math-review": colEarlyMathReviewPrim103TopUpQuestions,
  "col-eureka-math-3rd-8th-grade": colEurekaMath3rd8thGradePrim103TopUpQuestions,
  "col-eureka-math-foundations-3rd-8th-grade": colEurekaMathFoundations3rd8thGradePrim103TopUpQuestions,
  "col-get-ready-for-3rd-grade": colGetReadyFor3rdGradePrim103TopUpQuestions,
  "col-get-ready-for-4th-grade": colGetReadyFor4thGradePrim103TopUpQuestions,
  "col-get-ready-for-5th-grade": colGetReadyFor5thGradePrim103TopUpQuestions,
  "col-get-ready-for-6th-grade": colGetReadyFor6thGradePrim103TopUpQuestions,
  "col-times-tables": colTimesTablesPrim103TopUpQuestions,
  "col-word-builders": colWordBuildersPrim103TopUpQuestions,
  "dinosPrimary": dinosPrimaryPrim103TopUpQuestions,
  "elevenPlus": elevenPlusPrim103TopUpQuestions,
  "moneyBasics": [...moneyBasicsPrim103TopUpAQuestions, ...moneyBasicsPrim103TopUpBQuestions],
  "naplanYear3": naplanYear3Prim103TopUpQuestions,
  "naplanYear5": naplanYear5Prim103TopUpQuestions,
  "oceanPrimary": oceanPrimaryPrim103TopUpQuestions,
  "philosophyYear1": philosophyYear1Prim103TopUpQuestions,
  "philosophyYear2": philosophyYear2Prim103TopUpQuestions,
  "philosophyYear3": philosophyYear3Prim103TopUpQuestions,
  "philosophyYear4": philosophyYear4Prim103TopUpQuestions,
  "philosophyYear5": philosophyYear5Prim103TopUpQuestions,
  "philosophyYear6": philosophyYear6Prim103TopUpQuestions,
  "planetsPrimary": planetsPrimaryPrim103TopUpQuestions,
  "primary": [...primaryPrim103TopUpAQuestions, ...primaryPrim103TopUpBQuestions],
  "pslePrep": pslePrepPrim103TopUpQuestions,
  "readingVocab4th": [...readingVocab4thPrim103TopUpAQuestions, ...readingVocab4thPrim103TopUpBQuestions],
  "readingVocab5th": [...readingVocab5thPrim103TopUpAQuestions, ...readingVocab5thPrim103TopUpBQuestions],
  "scienceYear1": scienceYear1Prim103TopUpQuestions,
  "scienceYear2": scienceYear2Prim103TopUpQuestions,
  "scienceYear3": scienceYear3Prim103TopUpQuestions,
  "scienceYear4": scienceYear4Prim103TopUpQuestions,
  "scienceYear5": scienceYear5Prim103TopUpQuestions,
  "scienceYear6": scienceYear6Prim103TopUpQuestions,
  "timesTables": timesTablesPrim103TopUpQuestions,
  "wordBuilders": wordBuildersPrim103TopUpQuestions,
}
