// Auto-generated by _gen_univ103_aggregator.cjs — university 103-pass top-ups.
// Merged into university catalogs by loadQuestionCatalog (appended to matching trackId).
import type { Question } from './types'
import { algorithmsUniv103TopUpQuestions } from './algorithmsUniv103TopUp'
import { anatomyAndPhysiologyUniv103TopUpQuestions } from './anatomyAndPhysiologyUniv103TopUp'
import { apCalculusBcUniv103TopUpQuestions } from './apCalculusBcUniv103TopUp'
import { apEnvironmentalScienceUniv103TopUpQuestions } from './apEnvironmentalScienceUniv103TopUp'
import { artHistoryUniv103TopUpQuestions } from './artHistoryUniv103TopUp'
import { class11MathUniv103TopUpQuestions } from './class11MathUniv103TopUp'
import { class12MathUniv103TopUpQuestions } from './class12MathUniv103TopUp'
import { colClass11MathUniv103TopUpQuestions } from './col-class-11-mathUniv103TopUp'
import { colClass12MathUniv103TopUpQuestions } from './col-class-12-mathUniv103TopUp'
import { colCollegeAlgebraUniv103TopUpQuestions } from './col-college-algebraUniv103TopUp'
import { colEurekaMathPrecalculusUniv103TopUpQuestions } from './col-eureka-math-precalculusUniv103TopUp'
import { collegeAlgebraUniv103TopUpQuestions } from './collegeAlgebraUniv103TopUp'
import { comparativePracticalPoliticsUniv103TopUpQuestions } from './comparativePracticalPoliticsUniv103TopUp'
import { contemporaryEthicsUniv103TopUpQuestions } from './contemporaryEthicsUniv103TopUp'
import { dataStructuresUniv103TopUpQuestions } from './dataStructuresUniv103TopUp'
import { differentialEquationsUniv103TopUpQuestions } from './differentialEquationsUniv103TopUp'
import { discreteMathUniv103TopUpQuestions } from './discreteMathUniv103TopUp'
import { electricalEngineeringUniv103TopUpQuestions } from './electricalEngineeringUniv103TopUp'
import { englishComposition101Univ103TopUpQuestions } from './englishComposition101Univ103TopUp'
import { eurekaMathPrecalculusUniv103TopUpQuestions } from './eurekaMathPrecalculusUniv103TopUp'
import { financialAccountingUniv103TopUpQuestions } from './financialAccountingUniv103TopUp'
import { genBio1Univ103TopUpQuestions } from './genBio1Univ103TopUp'
import { genChem1Univ103TopUpQuestions } from './genChem1Univ103TopUp'
import { genPhys1Univ103TopUpQuestions } from './genPhys1Univ103TopUp'
import { generalBiology2Univ103TopUpQuestions } from './generalBiology2Univ103TopUp'
import { generalChemistry2Univ103TopUpQuestions } from './generalChemistry2Univ103TopUp'
import { generalPhysics2Univ103TopUpQuestions } from './generalPhysics2Univ103TopUp'
import { internationalRelationsUniv103TopUpQuestions } from './internationalRelationsUniv103TopUp'
import { introCSUniv103TopUpQuestions } from './introCSUniv103TopUp'
import { introToPsychologyUniv103TopUpQuestions } from './introToPsychologyUniv103TopUp'
import { introToSociologyUniv103TopUpQuestions } from './introToSociologyUniv103TopUp'
import { linearAlgebraUniv103TopUpQuestions } from './linearAlgebraUniv103TopUp'
import { logicCriticalThinkingUniv103TopUpQuestions } from './logicCriticalThinkingUniv103TopUp'
import { lsatUniv103TopUpQuestions } from './lsatUniv103TopUp'
import { marketingUniv103TopUpQuestions } from './marketingUniv103TopUp'
import { mathDiagnosticsUniv103TopUpAQuestions } from './mathDiagnosticsUniv103TopUpA'
import { mathDiagnosticsUniv103TopUpBQuestions } from './mathDiagnosticsUniv103TopUpB'
import { mcatUniv103TopUpQuestions } from './mcatUniv103TopUp'
import { multivariableCalculusUniv103TopUpQuestions } from './multivariableCalculusUniv103TopUp'
import { neuroscienceUniv103TopUpQuestions } from './neuroscienceUniv103TopUp'
import { organicChemistryUniv103TopUpQuestions } from './organicChemistryUniv103TopUp'
import { philSeniorUniv103TopUpAQuestions } from './philSeniorUniv103TopUpA'
import { philSeniorUniv103TopUpBQuestions } from './philSeniorUniv103TopUpB'
import { philosophyUniv103TopUpQuestions } from './philosophyUniv103TopUp'
import { researchMethodsUniv103TopUpQuestions } from './researchMethodsUniv103TopUp'
import { researchUniv103TopUpQuestions } from './researchUniv103TopUp'
import { softwareDesignUniv103TopUpQuestions } from './softwareDesignUniv103TopUp'
import { softwareFoundationsUniv103TopUpQuestions } from './softwareFoundationsUniv103TopUp'
import { sqlFoundationsUniv103TopUpQuestions } from './sqlFoundationsUniv103TopUp'

export const UNIVERSITY_103_TOPUPS: Record<string, Question[]> = {
  "algorithms": algorithmsUniv103TopUpQuestions,
  "anatomyAndPhysiology": anatomyAndPhysiologyUniv103TopUpQuestions,
  "apCalculusBc": apCalculusBcUniv103TopUpQuestions,
  "apEnvironmentalScience": apEnvironmentalScienceUniv103TopUpQuestions,
  "artHistory": artHistoryUniv103TopUpQuestions,
  "class11Math": class11MathUniv103TopUpQuestions,
  "class12Math": class12MathUniv103TopUpQuestions,
  "col-class-11-math": colClass11MathUniv103TopUpQuestions,
  "col-class-12-math": colClass12MathUniv103TopUpQuestions,
  "col-college-algebra": colCollegeAlgebraUniv103TopUpQuestions,
  "col-eureka-math-precalculus": colEurekaMathPrecalculusUniv103TopUpQuestions,
  "collegeAlgebra": collegeAlgebraUniv103TopUpQuestions,
  "comparativePracticalPolitics": comparativePracticalPoliticsUniv103TopUpQuestions,
  "contemporaryEthics": contemporaryEthicsUniv103TopUpQuestions,
  "dataStructures": dataStructuresUniv103TopUpQuestions,
  "differentialEquations": differentialEquationsUniv103TopUpQuestions,
  "discreteMath": discreteMathUniv103TopUpQuestions,
  "electricalEngineering": electricalEngineeringUniv103TopUpQuestions,
  "englishComposition101": englishComposition101Univ103TopUpQuestions,
  "eurekaMathPrecalculus": eurekaMathPrecalculusUniv103TopUpQuestions,
  "financialAccounting": financialAccountingUniv103TopUpQuestions,
  "genBio1": genBio1Univ103TopUpQuestions,
  "genChem1": genChem1Univ103TopUpQuestions,
  "genPhys1": genPhys1Univ103TopUpQuestions,
  "generalBiology2": generalBiology2Univ103TopUpQuestions,
  "generalChemistry2": generalChemistry2Univ103TopUpQuestions,
  "generalPhysics2": generalPhysics2Univ103TopUpQuestions,
  "internationalRelations": internationalRelationsUniv103TopUpQuestions,
  "introCS": introCSUniv103TopUpQuestions,
  "introToPsychology": introToPsychologyUniv103TopUpQuestions,
  "introToSociology": introToSociologyUniv103TopUpQuestions,
  "linearAlgebra": linearAlgebraUniv103TopUpQuestions,
  "logicCriticalThinking": logicCriticalThinkingUniv103TopUpQuestions,
  "lsat": lsatUniv103TopUpQuestions,
  "marketing": marketingUniv103TopUpQuestions,
  "mathDiagnostics": [...mathDiagnosticsUniv103TopUpAQuestions, ...mathDiagnosticsUniv103TopUpBQuestions],
  "mcat": mcatUniv103TopUpQuestions,
  "multivariableCalculus": multivariableCalculusUniv103TopUpQuestions,
  "neuroscience": neuroscienceUniv103TopUpQuestions,
  "organicChemistry": organicChemistryUniv103TopUpQuestions,
  "philSenior": [...philSeniorUniv103TopUpAQuestions, ...philSeniorUniv103TopUpBQuestions],
  "philosophy": philosophyUniv103TopUpQuestions,
  "research": researchUniv103TopUpQuestions,
  "researchMethods": researchMethodsUniv103TopUpQuestions,
  "softwareDesign": softwareDesignUniv103TopUpQuestions,
  "softwareFoundations": softwareFoundationsUniv103TopUpQuestions,
  "sqlFoundations": sqlFoundationsUniv103TopUpQuestions,
}
