// Auto-generated by _gen_univ103_aggregator.cjs — university 103-pass top-ups.
// Merged into university catalogs by loadQuestionCatalog (appended to matching trackId).
import { defaultQuestionScaffold } from './base'
import type { Question } from './types'
import { algorithmsUniv103TopUpQuestions } from './algorithmsUniv103TopUp'
import { anatomyAndPhysiologyUniv103TopUpQuestions } from './anatomyAndPhysiologyUniv103TopUp'
import { apCalculusBcUniv103TopUpQuestions } from './apCalculusBcUniv103TopUp'
import { apEnvironmentalScienceUniv103TopUpQuestions } from './apEnvironmentalScienceUniv103TopUp'
import { artHistoryUniv103TopUpQuestions } from './artHistoryUniv103TopUp'
import { class11MathUniv103TopUpQuestions } from './class11MathUniv103TopUp'
import { class12MathUniv103TopUpQuestions } from './class12MathUniv103TopUp'
import { colClass11MathUniv103TopUpQuestions } from './col-class-11-mathUniv103TopUp'
import { colClass12MathUniv103TopUpQuestions } from './col-class-12-mathUniv103TopUp'
import { colCollegeAlgebraUniv103TopUpQuestions } from './col-college-algebraUniv103TopUp'
import { colEurekaMathPrecalculusUniv103TopUpQuestions } from './col-eureka-math-precalculusUniv103TopUp'
import { collegeAlgebraUniv103TopUpQuestions } from './collegeAlgebraUniv103TopUp'
import { comparativePracticalPoliticsUniv103TopUpQuestions } from './comparativePracticalPoliticsUniv103TopUp'
import { contemporaryEthicsUniv103TopUpQuestions } from './contemporaryEthicsUniv103TopUp'
import { dataStructuresUniv103TopUpQuestions } from './dataStructuresUniv103TopUp'
import { differentialEquationsUniv103TopUpQuestions } from './differentialEquationsUniv103TopUp'
import { discreteMathUniv103TopUpQuestions } from './discreteMathUniv103TopUp'
import { electricalEngineeringUniv103TopUpQuestions } from './electricalEngineeringUniv103TopUp'
import { englishComposition101Univ103TopUpQuestions } from './englishComposition101Univ103TopUp'
import { eurekaMathPrecalculusUniv103TopUpQuestions } from './eurekaMathPrecalculusUniv103TopUp'
import { financialAccountingUniv103TopUpQuestions } from './financialAccountingUniv103TopUp'
import { genBio1Univ103TopUpQuestions } from './genBio1Univ103TopUp'
import { genChem1Univ103TopUpQuestions } from './genChem1Univ103TopUp'
import { genPhys1Univ103TopUpQuestions } from './genPhys1Univ103TopUp'
import { generalBiology2Univ103TopUpQuestions } from './generalBiology2Univ103TopUp'
import { generalChemistry2Univ103TopUpQuestions } from './generalChemistry2Univ103TopUp'
import { generalPhysics2Univ103TopUpQuestions } from './generalPhysics2Univ103TopUp'
import { internationalRelationsUniv103TopUpQuestions } from './internationalRelationsUniv103TopUp'
import { introCSUniv103TopUpQuestions } from './introCSUniv103TopUp'
import { introToPsychologyUniv103TopUpQuestions } from './introToPsychologyUniv103TopUp'
import { introToSociologyUniv103TopUpQuestions } from './introToSociologyUniv103TopUp'
import { linearAlgebraUniv103TopUpQuestions } from './linearAlgebraUniv103TopUp'
import { logicCriticalThinkingUniv103TopUpQuestions } from './logicCriticalThinkingUniv103TopUp'
import { lsatUniv103TopUpQuestions } from './lsatUniv103TopUp'
import { marketingUniv103TopUpQuestions } from './marketingUniv103TopUp'
import { mathDiagnosticsUniv103TopUpAQuestions } from './mathDiagnosticsUniv103TopUpA'
import { mathDiagnosticsUniv103TopUpBQuestions } from './mathDiagnosticsUniv103TopUpB'
import { mcatUniv103TopUpQuestions } from './mcatUniv103TopUp'
import { multivariableCalculusUniv103TopUpQuestions } from './multivariableCalculusUniv103TopUp'
import { neuroscienceUniv103TopUpQuestions } from './neuroscienceUniv103TopUp'
import { organicChemistryUniv103TopUpQuestions } from './organicChemistryUniv103TopUp'
import { philSeniorUniv103TopUpAQuestions } from './philSeniorUniv103TopUpA'
import { philSeniorUniv103TopUpBQuestions } from './philSeniorUniv103TopUpB'
import { philosophyUniv103TopUpQuestions } from './philosophyUniv103TopUp'
import { researchMethodsUniv103TopUpQuestions } from './researchMethodsUniv103TopUp'
import { researchUniv103TopUpQuestions } from './researchUniv103TopUp'
import { softwareDesignUniv103TopUpQuestions } from './softwareDesignUniv103TopUp'
import { softwareFoundationsUniv103TopUpQuestions } from './softwareFoundationsUniv103TopUp'
import { sqlFoundationsUniv103TopUpQuestions } from './sqlFoundationsUniv103TopUp'

const GENERIC_UNIVERSITY_103_HINTS = new Set([
  'Translate the question into the core concept first, then eliminate answers that do not match the wording.',
  ...(['Mathematics', 'Statistics', 'ML', 'Software', 'Research', 'Medical', 'University', 'Science'] as const).map(
    topic => defaultQuestionScaffold(topic, '__', '__').mentorHint,
  ),
])

function university103Hint(trackId: string, question: Question): string {
  const text = `${trackId} ${question.chapter} ${question.title} ${question.prompt}`.toLowerCase()

  if (text.includes('precalculus') || text.includes('calculus') || text.includes('algebra') || text.includes('equation') || text.includes('function')) {
    if (text.includes('derivative') || text.includes('integral') || text.includes('limit')) {
      return 'Identify the calculus object first: limit behavior, instantaneous rate, accumulated area, or a differential equation. Once the object is clear, choose the rule that fits its structure instead of matching on a familiar symbol.'
    }
    if (text.includes('trig') || text.includes('sine') || text.includes('cosine') || text.includes('unit circle')) {
      return 'For trigonometry, locate the angle relationship before calculating: quadrant, reference angle, period, or identity. A wrong answer often has the right number with the wrong sign or cycle.'
    }
    return 'Rewrite the prompt into the relationship it is testing: function behavior, graph feature, algebraic constraint, or rate of change. Then use the answer choices only after the structure of the problem is settled.'
  }

  if (text.includes('chem') || text.includes('mole') || text.includes('equilibrium') || text.includes('acid') || text.includes('redox') || text.includes('bond')) {
    if (text.includes('equilibrium') || text.includes('le chatelier')) {
      return 'For equilibrium, ask what disturbance was made and how the system can partially oppose it. Track whether the shift affects concentrations, pressure, temperature, or the equilibrium expression itself.'
    }
    if (text.includes('acid') || text.includes('base') || text.includes('ph') || text.includes('pka')) {
      return 'For acid-base reasoning, decide who donates or accepts the proton and compare pH with pKa when the prompt gives both. The favored species follows from that comparison, not from the name alone.'
    }
    return 'Chemistry questions are easier if you name the conserved quantity or driving force first: atoms, charge, moles, electrons, or energy. Keep units and particle counts visible so a plausible distractor cannot hide a mismatch.'
  }

  if (text.includes('biology') || text.includes('bio1') || text.includes('anatomy') || text.includes('physiology') || text.includes('cell') || text.includes('enzyme')) {
    return 'Start from structure and function: identify the molecule, cell part, tissue, or body system and ask what job it normally performs. The best answer should fit the level of organization in the prompt, not just mention a related biology term.'
  }

  if (text.includes('physics') || text.includes('phys1') || text.includes('circuit') || text.includes('voltage') || text.includes('force') || text.includes('field')) {
    if (text.includes('circuit') || text.includes('resistor') || text.includes('voltage') || text.includes('current')) {
      return 'For circuit items, decide whether components are in series or parallel before using equations. Then track which voltage, current, or equivalent resistance belongs to the part of the circuit being asked about.'
    }
    return 'Write down the physical quantity being asked for and the law connecting it to the givens. Units are a built-in check: force, energy, field, voltage, and acceleration cannot be swapped without changing the reasoning.'
  }

  if (text.includes('accounting') || text.includes('financial') || text.includes('debit') || text.includes('credit') || text.includes('statement')) {
    return 'In accounting, first classify the account and timing: asset, liability, equity, revenue, expense, or cash flow. Then check whether the entry preserves the accounting equation and matches when the event is recognized.'
  }

  if (text.includes('lsat') || text.includes('argument') || text.includes('assumption') || text.includes('weaken') || text.includes('logic')) {
    if (text.includes('weaken')) {
      return 'Find the argument bridge before reading the answer choices: evidence on one side, conclusion on the other. The best weakening answer attacks that bridge directly rather than merely sounding unfavorable.'
    }
    if (text.includes('assumption')) {
      return 'Ask what unstated idea the argument needs in order to move from its evidence to its conclusion. A necessary assumption is often modest; if you negate it, the argument should lose support.'
    }
    return 'Map the claim, evidence, and inference separately. Logical reasoning questions reward the answer that matches the argument role precisely, not the answer with the strongest wording.'
  }

  if (text.includes('composition') || text.includes('writing') || text.includes('source') || text.includes('rhetoric') || text.includes('thesis')) {
    return 'Composition questions usually test purpose, audience, evidence, and revision. Choose the answer that makes the writing more specific and better supported rather than simply more formal.'
  }

  if (text.includes('sociology') || text.includes('psychology') || text.includes('social')) {
    return 'Separate the scenario from the formal concept being tested: norm, institution, identity, method, or social structure. The correct choice should explain the pattern in the prompt without adding motives the prompt never gave.'
  }

  if (text.includes('research') || text.includes('study') || text.includes('experiment') || text.includes('causal') || text.includes('control')) {
    return 'Ask what claim the study is trying to support and whether the design can actually support it. Controls, comparison groups, sampling, confounders, and measurement validity determine how strong the conclusion can be.'
  }

  if (text.includes('data structure') || text.includes('algorithm') || text.includes('software') || text.includes('sql')) {
    return 'Translate the task into the operation being optimized: lookup, traversal, ordering, grouping, state, or persistence. The right technical choice should fit the constraint in the prompt, not just be a familiar tool.'
  }

  return 'Name the concept and the exact relationship the question is testing before looking at the choices. A strong answer will fit the wording of this scenario without smuggling in an extra assumption.'
}

function enrichUniversity103Hints(trackId: string, questions: Question[]): Question[] {
  return questions.map(question => (
    question.mentorHint && !GENERIC_UNIVERSITY_103_HINTS.has(question.mentorHint)
      ? question
      : { ...question, mentorHint: university103Hint(trackId, question) }
  ))
}

const RAW_UNIVERSITY_103_TOPUPS: Record<string, Question[]> = {
  "algorithms": algorithmsUniv103TopUpQuestions,
  "anatomyAndPhysiology": anatomyAndPhysiologyUniv103TopUpQuestions,
  "apCalculusBc": apCalculusBcUniv103TopUpQuestions,
  "apEnvironmentalScience": apEnvironmentalScienceUniv103TopUpQuestions,
  "artHistory": artHistoryUniv103TopUpQuestions,
  "class11Math": class11MathUniv103TopUpQuestions,
  "class12Math": class12MathUniv103TopUpQuestions,
  "col-class-11-math": colClass11MathUniv103TopUpQuestions,
  "col-class-12-math": colClass12MathUniv103TopUpQuestions,
  "col-college-algebra": colCollegeAlgebraUniv103TopUpQuestions,
  "col-eureka-math-precalculus": colEurekaMathPrecalculusUniv103TopUpQuestions,
  "collegeAlgebra": collegeAlgebraUniv103TopUpQuestions,
  "comparativePracticalPolitics": comparativePracticalPoliticsUniv103TopUpQuestions,
  "contemporaryEthics": contemporaryEthicsUniv103TopUpQuestions,
  "dataStructures": dataStructuresUniv103TopUpQuestions,
  "differentialEquations": differentialEquationsUniv103TopUpQuestions,
  "discreteMath": discreteMathUniv103TopUpQuestions,
  "electricalEngineering": electricalEngineeringUniv103TopUpQuestions,
  "englishComposition101": englishComposition101Univ103TopUpQuestions,
  "eurekaMathPrecalculus": eurekaMathPrecalculusUniv103TopUpQuestions,
  "financialAccounting": financialAccountingUniv103TopUpQuestions,
  "genBio1": genBio1Univ103TopUpQuestions,
  "genChem1": genChem1Univ103TopUpQuestions,
  "genPhys1": genPhys1Univ103TopUpQuestions,
  "generalBiology2": generalBiology2Univ103TopUpQuestions,
  "generalChemistry2": generalChemistry2Univ103TopUpQuestions,
  "generalPhysics2": generalPhysics2Univ103TopUpQuestions,
  "internationalRelations": internationalRelationsUniv103TopUpQuestions,
  "introCS": introCSUniv103TopUpQuestions,
  "introToPsychology": introToPsychologyUniv103TopUpQuestions,
  "introToSociology": introToSociologyUniv103TopUpQuestions,
  "linearAlgebra": linearAlgebraUniv103TopUpQuestions,
  "logicCriticalThinking": logicCriticalThinkingUniv103TopUpQuestions,
  "lsat": lsatUniv103TopUpQuestions,
  "marketing": marketingUniv103TopUpQuestions,
  "mathDiagnostics": [...mathDiagnosticsUniv103TopUpAQuestions, ...mathDiagnosticsUniv103TopUpBQuestions],
  "mcat": mcatUniv103TopUpQuestions,
  "multivariableCalculus": multivariableCalculusUniv103TopUpQuestions,
  "neuroscience": neuroscienceUniv103TopUpQuestions,
  "organicChemistry": organicChemistryUniv103TopUpQuestions,
  "philSenior": [...philSeniorUniv103TopUpAQuestions, ...philSeniorUniv103TopUpBQuestions],
  "philosophy": philosophyUniv103TopUpQuestions,
  "research": researchUniv103TopUpQuestions,
  "researchMethods": researchMethodsUniv103TopUpQuestions,
  "softwareDesign": softwareDesignUniv103TopUpQuestions,
  "softwareFoundations": softwareFoundationsUniv103TopUpQuestions,
  "sqlFoundations": sqlFoundationsUniv103TopUpQuestions,
}

export const UNIVERSITY_103_TOPUPS: Record<string, Question[]> = Object.fromEntries(
  Object.entries(RAW_UNIVERSITY_103_TOPUPS).map(([trackId, questions]) => [
    trackId,
    enrichUniversity103Hints(trackId, questions),
  ]),
)
