const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-animals-science-technology-audit.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaAnimalBiologyImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::animals::20',
  'opentriviaqa::animals::21',
  'opentriviaqa::animals::132',
  'opentriviaqa::animals::148',
  'opentriviaqa::animals::191',
  'opentriviaqa::animals::234',
  'opentriviaqa::animals::276',
  'opentriviaqa::animals::568',
  'opentriviaqa::animals::570',
  'opentriviaqa::animals::577',
  'opentriviaqa::animals::797',
  'opentriviaqa::animals::872',
  'opentriviaqa::animals::876',
  'opentriviaqa::animals::926',
  'opentriviaqa::animals::1065',
  'opentriviaqa::animals::1104',
  'opentriviaqa::animals::1209',
  'opentriviaqa::animals::1223',
  'opentriviaqa::animals::1241',
  'opentriviaqa::animals::1303',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\btrough\b/gi, 'through')
    .replace(/\bsharks\b/gi, "shark's")
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This choice does not fit the biology concept named in the prompt.',
      'Match the answer to the adaptation, physiology, reproduction, or ecology clue.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt_text} ${item.topicBucket}`.toLowerCase()
  if (/predator|prey|food chain|carnivore|omnivore|habitat|camouflage|defense|wetlands/.test(text)) {
    return 'Ecology and Adaptation'
  }
  if (/reproduce|eggs|respiration|blood|venom|electro|organ|hood|protein/.test(text)) {
    return 'Animal Structure and Function'
  }
  return item.topicBucket || 'Animal Biology'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_animal_biology_import.cjs.',
    '// Manual allowlist: stable animal-biology concept rows only, routed to AP Biology.',
    '',
    "export const openTriviaAnimalBiologyQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${352001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push('    source: \'OpenTriviaQA\',')
    lines.push(`    title: ${JSON.stringify(`Animal Biology ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed AP Biology animal-biology micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const items = audit.acceptedCandidates.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP Biology animal-biology questions.`)
}

main()
