const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opentriviaqa/opentriviaqa_questions.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaGeographyImported.ts')

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function promptLeaksAnswer(item) {
  const prompt = normalizeText(item.prompt_text).toLowerCase()
  const answer = normalizeText(item.correct_answer).toLowerCase()
  return answer.length > 3 && prompt.includes(answer)
}

const stalePromptPatterns = /\b(?:currently|today|this year|latest|newest|recent|president of|prime minister|ceo of|world record|ranked|which actor|which actress|movie|song|album|television|tv show|video game)\b/i
const nonGeographyPromptPatterns = /\b(?:national motto|national anthem|national flag|featured in the flag|richest city)\b/i

const geographyPatterns = [
  /\bcapital of\b/i,
  /\blongest river\b/i,
  /\briver\b/i,
  /\bmountain\b/i,
  /\bcontinent\b/i,
  /\bocean\b/i,
  /\bcountry\b/i,
  /\bcity\b/i,
  /\bisland\b/i,
  /\bsea\b/i,
  /\bdesert\b/i,
  /\bborder\b/i,
]

function chapterForPrompt(prompt) {
  if (/\bcapital of\b/i.test(prompt)) return 'World Capitals'
  if (/\briver|ocean|sea\b/i.test(prompt)) return 'Rivers and Oceans'
  if (/\bmountain|desert|island|continent\b/i.test(prompt)) return 'Physical Geography'
  if (/\bcountry|city|border\b/i.test(prompt)) return 'Countries and Regions'
  return 'World Geography'
}

function isUsable(item) {
  const prompt = normalizeText(item.prompt_text)
  return (
    item.category === 'geography' &&
    prompt.length >= 12 &&
    normalizeText(item.correct_answer) &&
    wrongChoices(item).length >= 2 &&
    !promptLeaksAnswer(item) &&
    !stalePromptPatterns.test(prompt) &&
    !nonGeographyPromptPatterns.test(prompt) &&
    geographyPatterns.some((pattern) => pattern.test(prompt))
  )
}

function titleForItem(item, index) {
  const prompt = normalizeText(item.prompt_text)
  if (prompt.length <= 58) return prompt
  return `OpenTrivia Geography ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_geography_import.cjs from data/raw_collections/opentriviaqa.',
    '// Keeps only stable geography prompts with structured wrong choices and no answer leakage.',
    '',
    "export const openTriviaGeographyQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const prompt = normalizeText(item.prompt_text)
    lines.push('  {')
    lines.push(`    id: ${336001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForPrompt(prompt))},`)
    lines.push(`    title: ${JSON.stringify(titleForItem(item, index))},`)
    lines.push(`    prompt: ${JSON.stringify(prompt)},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item).map((choice) => [choice, 'This is one of the source distractors, but it does not match the geographic clue in the prompt.', 'Anchor on the place, landform, capital, or region described in the question.']))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Correct answer: ${normalizeText(item.correct_answer)}.`)},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = (payload.items ?? []).filter(isUsable)
  if (items.length < 300) {
    throw new Error(`Expected at least 300 usable OpenTriviaQA geography questions, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenTriviaQA geography questions.`)
}

main()
