const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opentriviaqa/opentriviaqa_questions.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaBrainTeasersImported.ts')

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function isOrdinaryTrivia(item) {
  const prompt = normalizeText(item.prompt_text).toLowerCase()
  return /\b(proverb|which of these is true about|how does this proverb|who invented|capital of|what year|which country|which city|which animal|what is the name of|sleep of zebras)\b/.test(prompt)
}

function isUsable(item) {
  return (
    item.category === 'brain-teasers' &&
    normalizeText(item.prompt_text).length > 20 &&
    normalizeText(item.correct_answer) &&
    wrongChoices(item).length >= 1 &&
    !isOrdinaryTrivia(item)
  )
}

function titleForItem(item, index) {
  const prompt = normalizeText(item.prompt_text)
  if (prompt.length <= 58) return prompt
  return `OpenTrivia Brain Teaser ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_brain_teasers_import.cjs from data/raw_collections/opentriviaqa.',
    '// Keeps only the brain-teasers category and filters obvious ordinary trivia/proverb rows.',
    '',
    "export const openTriviaBrainTeaserQuestions = makeQuestionBank('Fun', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${334001 + index},`)
    lines.push("    chapter: 'Brain Teasers',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item, index))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item).map((choice) => [choice, 'This answer misses the trick, wording constraint, or arithmetic hidden in the prompt.', 'Read the wording literally and check whether the obvious interpretation is being baited.']))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Correct answer: ${normalizeText(item.correct_answer)}.`)},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = (payload.items ?? []).filter(isUsable)
  if (items.length < 150) {
    throw new Error(`Expected at least 150 usable OpenTriviaQA brain teasers, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenTriviaQA brain teaser questions.`)
}

main()
