const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opendsa/opendsa_exercises.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openDsaAlgorithmsImported.ts')

const algorithmCollections = new Set([
  'open-dsa::abo',
  'open-dsa::alganal',
  'open-dsa::binary',
  'open-dsa::cmp',
  'open-dsa::graph',
  'open-dsa::hashing',
  'open-dsa::indexing',
  'open-dsa::list',
  'open-dsa::np',
  'open-dsa::recurtutor',
  'open-dsa::searching',
  'open-dsa::senioralganal',
  'open-dsa::sorting',
])

const chapterByCollection = {
  'open-dsa::abo': 'Algorithm Analysis',
  'open-dsa::alganal': 'Algorithm Analysis',
  'open-dsa::binary': 'Binary Trees',
  'open-dsa::cmp': 'Comparing Algorithms',
  'open-dsa::graph': 'Graphs',
  'open-dsa::hashing': 'Hashing',
  'open-dsa::indexing': 'Indexing',
  'open-dsa::list': 'Lists and Linked Structures',
  'open-dsa::np': 'NP and Complexity',
  'open-dsa::recurtutor': 'Recursion',
  'open-dsa::searching': 'Searching',
  'open-dsa::senioralganal': 'Advanced Algorithm Analysis',
  'open-dsa::sorting': 'Sorting',
}

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .trim()
}

function jsString(value) {
  return JSON.stringify(value)
}

function wrongChoices(item) {
  const correct = normalizeText(item.solution_text).toLowerCase()
  const seen = new Set([correct])
  return (item.choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function promptLeaksAnswer(item) {
  const prompt = normalizeText(item.prompt_text).toLowerCase()
  const answer = normalizeText(item.solution_text).toLowerCase()
  return answer.length > 3 && prompt.includes(answer)
}

function promptMissingRequiredContext(item) {
  return /^Determine the proper relationship between the following pair of functions\.?$/i.test(
    normalizeText(item.prompt_text),
  )
}

function isUsable(item) {
  return (
    algorithmCollections.has(item.collection_id) &&
    normalizeText(item.prompt_text) &&
    normalizeText(item.solution_text) &&
    wrongChoices(item).length >= 2 &&
    !promptLeaksAnswer(item) &&
    !promptMissingRequiredContext(item)
  )
}

function titleForItem(item, index) {
  const title = normalizeText(item.title)
  if (title) return title
  return `OpenDSA Algorithm ${index + 1}`
}

function buildWrongTriples(item) {
  return wrongChoices(item).map((choice) => [
    choice,
    'This matches a nearby algorithm or data-structure idea, but not the exact condition in the prompt.',
    'Track the operation, complexity class, or structure invariant being tested before choosing.',
  ])
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opendsa_algorithms_import.cjs from data/raw_collections/opendsa.',
    '// Only imports algorithm items with distinct answer choices and enough prompt context to be playable.',
    '',
    "export const openDsaAlgorithmQuestions = makeQuestionBank('Software', [",
  ]

  items.forEach((item, index) => {
    const lesson = [
      `Source: OpenDSA (${item.source_id}).`,
      `Correct answer: ${normalizeText(item.solution_text)}.`,
    ].join(' ')

    lines.push('  {')
    lines.push(`    id: ${330001 + index},`)
    lines.push(`    chapter: ${jsString(chapterByCollection[item.collection_id] ?? 'Algorithms')},`)
    lines.push(`    title: ${jsString(titleForItem(item, index))},`)
    lines.push(`    prompt: ${jsString(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${jsString(normalizeText(item.solution_text))},`)
    lines.push(`    wrong: ${jsString(buildWrongTriples(item))},`)
    lines.push(`    lesson: ${jsString(lesson)},`)
    lines.push("    source: 'OpenDSA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const rawItems = payload.items ?? []
  const items = rawItems.filter(isUsable)

  if (items.length < 200) {
    throw new Error(`Expected at least 200 usable OpenDSA algorithm questions, found ${items.length}.`)
  }

  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenDSA algorithm questions.`)
}

main()
