const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opendsa/opendsa_exercises.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openDsaBridgeCourseImported.ts')

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.solution_text).toLowerCase()
  const seen = new Set([correct])
  return (item.choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function promptLeaksAnswer(item) {
  const prompt = normalizeText(item.prompt_text).toLowerCase()
  const answer = normalizeText(item.solution_text).toLowerCase()
  return answer.length > 3 && prompt.includes(answer)
}

function hasTemplatePlaceholder(item) {
  return [item.prompt_text, item.solution_text, ...wrongChoices(item)]
    .map(normalizeText)
    .some((value) => /\b(?:CHOICES|ANSWER|INDEX|VAR\w*|FRAGMENT)\b|\{[A-Za-z_][^}]*\}/.test(value))
}

function hasMissingContext(item) {
  const prompt = normalizeText(item.prompt_text)
  return /(placeholder|following code|code is executed|what kind of variable is label|depicted below|diagram below|diagram above|UML diagram|simplified UML|demo|given the array:?$|Review the scenario below|case study|which of the following 5 implementations|alternate way to write remove|\bA\)\s*B\)\s*C\)|refer back|linked chain below|Given:|^Given |Based on |Based on ListInteface|Based on the described|Based on the insertion|Trace the following method|following method given|following references|following Java statements|following statements execute|after the following statements|queue look like|front of the deque after these statements)/i.test(prompt)
}

function hasCourseAdminText(item) {
  return [item.prompt_text, item.solution_text, ...wrongChoices(item)]
    .map(normalizeText)
    .some((value) => /\b(?:CS\s*2114|CS2114|WebCAT|Piazza|GlobeTrotters|course instructors?|lab section|support projects|functionDefinition|functionCalls|CorrectAnswer|option\d+|Correct Option)\b/i.test(value))
}

function isUsable(item) {
  return (
    item.collection_id === 'open-dsa::mengbridgecourse' &&
    normalizeText(item.prompt_text).length >= 20 &&
    normalizeText(item.solution_text) &&
    wrongChoices(item).length >= 2 &&
    !promptLeaksAnswer(item) &&
    !hasTemplatePlaceholder(item) &&
    !hasMissingContext(item) &&
    !hasCourseAdminText(item)
  )
}

function chapterForItem(item) {
  const text = `${item.title} ${item.prompt_text}`
  if (/bag|list|linked|queue|stack|iterator|node/i.test(text)) return 'Core Data Structures'
  if (/sort|search|complexity|recursive|recursion|algorithm/i.test(text)) return 'Algorithms and Complexity'
  if (/exception|junit|test|generic|java/i.test(text)) return 'Java Programming Foundations'
  return 'Software Engineering Bridge'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opendsa_bridge_course_import.cjs from data/raw_collections/opendsa.',
    '// Keeps only self-contained Meng Bridge Course questions with no omitted diagrams/code context.',
    '',
    "export const openDsaBridgeCourseQuestions = makeQuestionBank('Software', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item).map((choice) => [
      choice,
      'This is a plausible CS bridge-course answer, but it misses the data-structure, Java, or algorithm rule in the prompt.',
      'Identify the exact operation, abstraction, or complexity rule before choosing.',
    ])
    lines.push('  {')
    lines.push(`    id: ${335001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push(`    title: ${JSON.stringify(normalizeText(item.title) || `OpenDSA Bridge Course ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.solution_text))},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenDSA (${item.source_id}). Correct answer: ${normalizeText(item.solution_text)}.`)},`)
    lines.push("    source: 'OpenDSA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = (payload.items ?? []).filter(isUsable)
  if (items.length < 40) {
    throw new Error(`Expected at least 40 usable OpenDSA bridge-course questions, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenDSA bridge-course questions.`)
}

main()
