const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/ims_tutorials/ims_tutorials_questions.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/imsTutorialsImported.ts')

const chapterByCollectionId = {
  'ims-tutorials::01-data': 'Data and Study Design',
  'ims-tutorials::02-explore': 'Exploratory Data Analysis',
  'ims-tutorials::03-model': 'Statistical Modeling',
  'ims-tutorials::04-foundations': 'Probability Foundations',
  'ims-tutorials::05-infer': 'Statistical Inference',
  'ims-tutorials::06-model-infer': 'Model-Based Inference',
}

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .trim()
}

function titleFromPrompt(prompt, index) {
  const cleaned = normalizeText(prompt)
    .replace(/[?.!:;]+$/g, '')
    .replace(/^Which of the following\s+/i, '')
    .replace(/^Which\s+/i, '')
    .replace(/^What\s+/i, '')

  if (!cleaned) return `IMS Tutorial ${index}`
  if (cleaned.length <= 58) return cleaned
  return `${cleaned.slice(0, 55).trim()}...`
}

function jsString(value) {
  return JSON.stringify(value)
}

function buildWrongTriples(item) {
  return item.choices
    .filter((choice) => choice !== item.correct_choice)
    .map((choice) => [
      choice,
      'This is one of the source distractors, but it does not match the statistical setup.',
      'Check the study design, variable type, model output, or inference condition being tested.',
    ])
}

function validateItems(items) {
  const problems = []
  for (const item of items) {
    if (!normalizeText(item.prompt_text)) problems.push(`${item.source_id}: missing prompt`)
    if (!Array.isArray(item.choices) || item.choices.length < 2) {
      problems.push(`${item.source_id}: fewer than two choices`)
    }
    if (!item.choices?.includes(item.correct_choice)) {
      problems.push(`${item.source_id}: correct choice is not in choices`)
    }
  }

  if (problems.length > 0) {
    throw new Error(`IMS Tutorials import validation failed:\n${problems.join('\n')}`)
  }
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_ims_tutorials_import.cjs from data/raw_collections/ims_tutorials.',
    '// Keep these questions source-traceable; edit the miner/raw data or generator rather than hand-editing this file.',
    '',
    'export const imsTutorialsImportedQuestions = makeQuestionBank(\'Statistics\', [',
  ]

  items.forEach((item, index) => {
    const id = 310001 + index
    const chapter = chapterByCollectionId[item.collection_id] ?? 'IMS Tutorials'
    const title = titleFromPrompt(item.prompt_text, index + 1)
    const lesson = [
      `Source: IMS Tutorials (${item.source_id}).`,
      `Correct answer: ${item.correct_choice}.`,
    ].join(' ')

    lines.push('  {')
    lines.push(`    id: ${id},`)
    lines.push(`    chapter: ${jsString(chapter)},`)
    lines.push(`    title: ${jsString(title)},`)
    lines.push(`    prompt: ${jsString(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${jsString(item.correct_choice)},`)
    lines.push(`    wrong: ${jsString(buildWrongTriples(item))},`)
    lines.push(`    lesson: ${jsString(lesson)},`)
    lines.push("    source: 'IMS Tutorials',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = payload.items ?? []
  validateItems(items)
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} IMS Tutorials questions to ${path.relative(repoRoot, outputPath)}.`)
}

main()
