const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/openintro_stats_slides/openintro_stats_slides_questions.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openIntroStatsSlidesImported.ts')

const chapterBySlug = {
  chp_1: 'Data Basics and Study Design',
  chp_2: 'Exploring Data',
  chp_3: 'Probability',
  chp_4: 'Distributions',
  chp_5: 'Foundations for Inference',
  chp_6: 'Inference for Categorical Data',
  chp_7: 'Inference for Numerical Data',
  chp_8: 'Linear Regression',
  chp_9: 'Multiple Regression',
}

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function jsString(value) {
  return JSON.stringify(value)
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_choice).toLowerCase()
  const seen = new Set([correct])
  return (item.choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function hasMissingContext(item) {
  const prompt = normalizeText(item.prompt_text)
  return /\b(on the right|shown below|above|following table|following plot|scatterplot|histogram|simulation you just ran|clicker question|using the applet|the data shown|on this slide|this woman|this specific woman|these data|what percent of bottles|this linear model|the model output given|reference level|what is the conclusion|appropriate \$t|equivalent confidence level for a one-sided|given beauty score|this confidence interval|this hypothesis test|we just calculated|this interval|this p-value|this regression model|this model|the outlier|which of following|based on the model output)\b/i.test(prompt)
}

function hasMangledMath(item) {
  const values = [item.prompt_text, item.correct_choice, ...(item.choices ?? [])].map(normalizeText)
  return values.some((value) => (
    value === '[]' ||
    /\$\s*=|\$\s*\$|\$\s+[0-9]|[0-9]\s+\$|\\includegraphics|\\begin|\\end|\{[^}]*\}| n n|0\.255 2|0\.2 3|0\.8 3|point estimate ME|\$0\.9014 2\.06|%\(|\^ th/.test(value)
  ))
}

function isUsable(item) {
  return (
    normalizeText(item.prompt_text) &&
    normalizeText(item.correct_choice) &&
    wrongChoices(item).length >= 2 &&
    !hasMissingContext(item) &&
    !hasMangledMath(item)
  )
}

function titleForItem(item, index) {
  const prompt = normalizeText(item.prompt_text)
  if (prompt.length <= 62) return prompt
  return `OpenIntro Statistics Slide Question ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_openintro_stats_slides_import.cjs from data/raw_collections/openintro_stats_slides.',
    '// Keeps only standalone fixed-choice slide questions with clean prompt context.',
    '',
    "export const openIntroStatsSlidesQuestions = makeQuestionBank('Statistics', [",
  ]

  items.forEach((item, index) => {
    const lesson = `Source: OpenIntro Statistics Slides (${item.source_id}). Correct answer: ${normalizeText(item.correct_choice)}.`
    lines.push('  {')
    lines.push(`    id: ${332001 + index},`)
    lines.push(`    chapter: ${jsString(chapterBySlug[item.chapter_slug] ?? 'Statistics')},`)
    lines.push(`    title: ${jsString(titleForItem(item, index))},`)
    lines.push(`    prompt: ${jsString(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${jsString(normalizeText(item.correct_choice))},`)
    lines.push(`    wrong: ${jsString(wrongChoices(item).map((choice) => [choice, 'This is a plausible statistics distractor, but it misses the condition or interpretation in the prompt.', 'Name the variable type, sampling issue, distribution, or inference rule being tested first.']))},`)
    lines.push(`    lesson: ${jsString(lesson)},`)
    lines.push("    source: 'OpenIntro',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = (payload.items ?? []).filter(isUsable)
  if (items.length < 20) {
    throw new Error(`Expected at least 20 usable OpenIntro slide questions, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenIntro Statistics slide questions.`)
}

main()
