const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opendsa/opendsa_exercises.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openDsaFormalLanguagesImported.ts')

const collectionIds = new Set(['open-dsa::fla', 'open-dsa::pl'])

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.solution_text).toLowerCase()
  const seen = new Set([correct])
  return (item.choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function promptLeaksAnswer(item) {
  const prompt = normalizeText(item.prompt_text).toLowerCase()
  const answer = normalizeText(item.solution_text).toLowerCase()
  return answer.length > 3 && prompt.includes(answer)
}

function hasPlaceholderText(item) {
  return [item.title, item.prompt_text, item.solution_text, ...wrongChoices(item)]
    .map(normalizeText)
    .some((value) => /\b(?:CHOICES|ANSWER|CorrectAnswer|correctAnswer|Option\d+|option\d+|INDEX|VAR\w*|FRAGMENT|functionDefinition|functionCalls)\b|\{[A-Za-z_][^}]*\}/.test(value))
}

function hasMissingExternalContext(item) {
  const prompt = normalizeText(item.prompt_text)
  return (
    /(following abstract syntax tree|following Jison grammar|following λ expression|following expressions|following function definitions|following definition|following JavaScript expression|following JavaScript code|following Java program|following SLang|given the following code|following code|consider the following five snippets|Recall the main function|type-inference response)/i.test(prompt) ||
    /(following grammar for a language L\s*:|following fragment of a BNF grammar\s*:)$/i.test(prompt)
  )
}

function isUsable(item) {
  return (
    collectionIds.has(item.collection_id) &&
    normalizeText(item.prompt_text) &&
    normalizeText(item.solution_text) &&
    wrongChoices(item).length >= 2 &&
    !promptLeaksAnswer(item) &&
    !hasPlaceholderText(item) &&
    !hasMissingExternalContext(item)
  )
}

function chapterForItem(item) {
  if (item.collection_id === 'open-dsa::fla') return 'Formal Languages and Automata'
  if (/lambda|church|fp\.|cons|hd|tl|reduce/i.test(`${item.title} ${item.prompt_text}`)) return 'Functional Programming and Lambda Calculus'
  return 'Programming Languages'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opendsa_formal_languages_import.cjs from data/raw_collections/opendsa.',
    '// Keeps only self-contained formal-language and programming-language questions.',
    '',
    "export const openDsaFormalLanguagesQuestions = makeQuestionBank('Software', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${333001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push(`    title: ${JSON.stringify(normalizeText(item.title) || `OpenDSA Formal Languages ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.solution_text))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item).map((choice) => [choice, 'This is a nearby formal-language or programming-language option, but it does not satisfy the grammar, evaluation, or definition in the prompt.', 'Work from the grammar or language rule stated in the prompt rather than matching surface syntax.']))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenDSA (${item.source_id}). Correct answer: ${normalizeText(item.solution_text)}.`)},`)
    lines.push("    source: 'OpenDSA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = (payload.items ?? []).filter(isUsable)
  if (items.length < 10) {
    throw new Error(`Expected at least 10 usable OpenDSA formal-language questions, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenDSA formal-language questions.`)
}

main()
