const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaLiteratureFinalIdentityImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::literature::171',
  'opentriviaqa::literature::240',
  'opentriviaqa::literature::320',
  'opentriviaqa::literature::321',
  'opentriviaqa::literature::322',
  'opentriviaqa::literature::359',
  'opentriviaqa::literature::406',
  'opentriviaqa::literature::410',
  'opentriviaqa::literature::412',
  'opentriviaqa::literature::1064',
  'opentriviaqa::literature::1067',
  'opentriviaqa::literature::1070',
  'opentriviaqa::literature::1074',
  'opentriviaqa::literature::1078',
  'opentriviaqa::literature::1124',
  'opentriviaqa::literature::1126',
  'opentriviaqa::literature::1130',
  'opentriviaqa::literature::1131',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bEarnest Hemingway\b/g, 'Ernest Hemingway')
    .replace(/\bHuckleberry Finn\b/g, 'Huckleberry Finn')
    .replace(/\bI Lay dying\b/g, 'I Lay Dying')
    .replace(/\bShakespeares\b/g, "Shakespeare's")
    .replace(/\bPuddnhead Willson\b/g, 'Puddnhead Wilson')
    .replace(/\bThe Old Mean and the Sea\b/g, 'The Old Man and the Sea')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => !/^(all|none) of these$/i.test(choice))
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This answer belongs to a different novel, poet, or literary figure.',
      'Match the named clue in the prompt to the specific author, character, or work.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/shakespeare|hamlet|romeo|claudius|othello|king lear|midsummer|twelfth night/.test(text)) return 'Shakespeare: Plays and Characters'
  if (/twain|salinger|hemingway|faulkner|ludlum|bronte|jane eyre|grapes of wrath|atlas shrugged|moby dick/.test(text)) return 'Canonical Fiction'
  if (/poe|eliot|plath|frost|southey/.test(text)) return 'Modernism and Poetry'
  return 'AP English Literature Foundations'
}

function titleForItem(item, index) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/atlas shrugged/.test(text)) return 'Atlas Shrugged'
  if (/conqueror worm|poe/.test(text)) return 'Edgar Allan Poe'
  if (/maria|katherine|mary|pride and prejudice/.test(text)) return 'Pride and Prejudice'
  if (/jewel/.test(text)) return 'As I Lay Dying'
  if (/wounded/.test(text)) return 'Hemingway'
  if (/across the river/.test(text)) return 'Across the River and Into the Trees'
  if (/dangerous summer/.test(text)) return 'The Dangerous Summer'
  if (/rochester/.test(text)) return 'Jane Eyre'
  if (/frederic henry/.test(text)) return 'A Farewell to Arms'
  if (/angel clare/.test(text)) return "Tess of the d'Urbervilles"
  if (/hamlet/.test(text)) return 'Hamlet'
  if (/road to gandolfo/.test(text)) return 'Robert Ludlum'
  if (/huckleberry finn/.test(text)) return 'Huckleberry Finn'
  if (/letters from the earth/.test(text)) return 'Letters from the Earth'
  if (/innocents abroad/.test(text)) return 'The Innocents Abroad'
  if (/roughing it/.test(text)) return 'Roughing It'
  return `Literature Anchor ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_literature_final_identity_import.cjs.',
    '// Manual allowlist: conservative final identity batch from the remaining durable rows.',
    '',
    "export const openTriviaLiteratureFinalIdentityQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    const correct = normalizeText(item.correct_answer)
    if (/^(all|none) of these$/i.test(correct)) throw new Error(`Bad correct answer for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${366001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item, index))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(correct)},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the AP English Literature final identity micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const rows = audit.courses['AP English Literature/Humanities'] || []
  const items = rows.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP English Literature final identity questions.`)
}

main()
