const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const candidatesPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaLiteraryFormsShakespeareImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::literature::517',
  'opentriviaqa::literature::544',
  'opentriviaqa::literature::596',
  'opentriviaqa::literature::597',
  'opentriviaqa::literature::699',
  'opentriviaqa::literature::700',
  'opentriviaqa::literature::701',
  'opentriviaqa::literature::702',
  'opentriviaqa::literature::703',
  'opentriviaqa::literature::704',
  'opentriviaqa::literature::705',
  'opentriviaqa::literature::707',
  'opentriviaqa::literature::717',
  'opentriviaqa::literature::718',
  'opentriviaqa::literature::719',
  'opentriviaqa::literature::720',
  'opentriviaqa::literature::721',
  'opentriviaqa::literature::722',
  'opentriviaqa::literature::724',
  'opentriviaqa::literature::751',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bShakespeares\b/g, "Shakespeare's")
    .replace(/\bHamlets\b/g, "Hamlet's")
    .replace(/\bRomeos\b/g, "Romeo's")
    .replace(/\bHerman Melvilles\b/g, "Herman Melville's")
    .replace(/\bMary Shelleys\b/g, "Mary Shelley's")
    .replace(/\bKafkas\b/g, "Kafka's")
    .replace(/\bpersons\b/g, "person's")
    .replace(/\bhusbands\b/g, "husband's")
    .replace(/\bMIranda\b/g, 'Miranda')
    .replace(/\bbisody\b/g, 'stanza')
    .replace(/\bProsdic\b/g, 'Prosodic')
    .replace(/\bShwa\b/g, 'Schwa')
    .replace(/\bthe third have five\b/g, 'the third has five')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This choice does not match the literary form, character, work, or author clue in the prompt.',
      'Anchor the answer to the named play, novel, poem form, or character relationship.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/shakespeare|romeo|juliet|lear|twelfth night|macbeth|hamlet|globe theatre/.test(text)) return 'Shakespeare and Drama'
  if (/poem|poetry|sonnet|couplet|haiku|caesura|epic|acrostic/.test(text)) return 'Poetry Forms and Terms'
  if (/kafka|austen|cervantes|steinbeck/.test(text)) return 'Novel Landmarks'
  return 'Literary Forms and Canon'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_literary_forms_shakespeare_import.cjs.',
    '// Manual allowlist: literary forms, Shakespeare characters, and durable novel landmarks only.',
    '',
    "export const openTriviaLiteraryFormsShakespeareQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${356001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(`Literary Forms and Shakespeare ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed literary-forms/Shakespeare micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(candidatesPath, 'utf8'))
  const rows = payload.courses['AP English Literature/Humanities'] ?? []
  const items = rows.filter((row) => allowedSourceIds.has(row.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} literary forms/Shakespeare questions.`)
}

main()
