const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaArtPhilosophyExtensionImported.ts')

const artSourceIds = new Set([
  'opentriviaqa::humanities::375',
  'opentriviaqa::humanities::698',
  'opentriviaqa::humanities::702',
  'opentriviaqa::humanities::703',
  'opentriviaqa::humanities::743',
  'opentriviaqa::humanities::875',
  'opentriviaqa::humanities::876',
  'opentriviaqa::humanities::927',
])

const philosophySourceIds = new Set([
  'opentriviaqa::humanities::935',
  'opentriviaqa::humanities::1023',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bMichelangelos\b/g, "Michelangelo's")
    .replace(/\bLeonardos\b/g, "Leonardo's")
    .replace(/\bEdward Hoppers\b/g, "Edward Hopper's")
    .replace(/\bSalvador Dalis\b/g, "Salvador Dali's")
    .replace(/\bRembrandts\b/g, "Rembrandt's")
    .replace(/\bDa Vinci\b/g, 'da Vinci')
    .replace(/\bMichelangello\b/g, 'Michelangelo')
    .replace(/\bMetropolian\b/g, 'Metropolitan')
    .replace(/\bDeaths Head\b/g, "Death's Head")
    .replace(/\bLady With Ermine\b/g, 'Lady with an Ermine')
    .replace(/\bNicolaes Tulp\b/g, 'Nicolaes Tulp')
    .replace(/\bSpinoza\b/g, 'Spinoza')
    .replace(/\bSeventeenth Century\b/g, 'seventeenth-century')
    .replace(/\bChurch\b/g, 'community')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => !/^(all|none) of these$/i.test(choice))
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This option does not match the art-history or philosophy clue in the prompt.',
      'Anchor the answer to the named artist, work, movement, philosopher, or concept.',
    ])
}

function artChapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/baroque/.test(text)) return 'Baroque and Style Vocabulary'
  if (/mona lisa|leonardo|vasari|raphael/.test(text)) return 'Renaissance and Mona Lisa'
  if (/nighthawks|dali|surrealist|rembrandt|anatomy lesson/.test(text)) return 'Modern and Early Modern Works'
  return 'Art History Foundations'
}

function philosophyChapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/confucius|proverb/.test(text)) return 'Classical Philosophy'
  if (/spinoza|rationalist|mind and body/.test(text)) return 'Early Modern Philosophy'
  return 'Philosophy Foundations'
}

function titleForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/baroque/.test(text)) return 'Baroque'
  if (/mona lisa|florentine/.test(text)) return 'Mona Lisa'
  if (/raphael/.test(text)) return 'Raphael and the Mona Lisa'
  if (/vasari/.test(text)) return 'Giorgio Vasari'
  if (/nighthawks/.test(text)) return 'Nighthawks'
  if (/lobster telephone/.test(text)) return 'Dali and Surrealist Objects'
  if (/lady with/.test(text)) return 'Dali Attribution'
  if (/anatomy lesson/.test(text)) return 'Rembrandt Anatomy Lesson'
  if (/confucius/.test(text)) return 'Confucius'
  if (/spinoza/.test(text)) return 'Spinoza'
  return 'Art and Philosophy Extension'
}

function buildQuestionLines(items, idStart, chapterFn, lessonLabel) {
  const lines = []
  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    const correct = normalizeText(item.correct_answer)
    if (/^(all|none) of these$/i.test(correct)) throw new Error(`Bad correct answer for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${idStart + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterFn(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(correct)},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed ${lessonLabel} extension micro-batch.`)},`)
    lines.push('  },')
  })
  return lines
}

function buildOutput(artItems, philosophyItems) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_art_philosophy_extension_import.cjs.',
    '// Manual allowlist: stable named art-history and philosophy rows only.',
    '',
    "export const openTriviaArtHistorySecondExtensionQuestions = makeQuestionBank('University', [",
    ...buildQuestionLines(artItems, 365001, artChapterForItem, 'Art History'),
    '])',
    '',
    "export const openTriviaPhilosophyExtensionQuestions = makeQuestionBank('University', [",
    ...buildQuestionLines(philosophyItems, 366001, philosophyChapterForItem, 'Philosophy'),
    '])',
    '',
  ]
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const rows = audit.courses['AP Art History/Philosophy'] || []
  const artItems = rows.filter((item) => artSourceIds.has(item.source_id))
  const philosophyItems = rows.filter((item) => philosophySourceIds.has(item.source_id))
  if (artItems.length !== artSourceIds.size) throw new Error(`Expected ${artSourceIds.size} art rows, found ${artItems.length}.`)
  if (philosophyItems.length !== philosophySourceIds.size) throw new Error(`Expected ${philosophySourceIds.size} philosophy rows, found ${philosophyItems.length}.`)
  fs.writeFileSync(outputPath, buildOutput(artItems, philosophyItems), 'utf8')
  console.log(`Wrote ${artItems.length} Art History and ${philosophyItems.length} Philosophy questions.`)
}

main()
