const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const candidatesPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaUsHistoryExtensionImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::history::132',
  'opentriviaqa::history::133',
  'opentriviaqa::history::143',
  'opentriviaqa::history::150',
  'opentriviaqa::history::152',
  'opentriviaqa::history::181',
  'opentriviaqa::history::290',
  'opentriviaqa::history::297',
  'opentriviaqa::history::301',
  'opentriviaqa::history::426',
  'opentriviaqa::history::427',
  'opentriviaqa::history::453',
  'opentriviaqa::history::454',
  'opentriviaqa::history::554',
  'opentriviaqa::history::560',
  'opentriviaqa::history::801',
  'opentriviaqa::history::813',
  'opentriviaqa::history::814',
  'opentriviaqa::history::840',
  'opentriviaqa::history::841',
  'opentriviaqa::history::844',
  'opentriviaqa::history::847',
  'opentriviaqa::history::848',
  'opentriviaqa::history::882',
  'opentriviaqa::history::1091',
  'opentriviaqa::history::1098',
  'opentriviaqa::history::1104',
  'opentriviaqa::history::1105',
  'opentriviaqa::history::1106',
  'opentriviaqa::history::1108',
  'opentriviaqa::history::1109',
  'opentriviaqa::history::1268',
  'opentriviaqa::history::1277',
  'opentriviaqa::history::1347',
  'opentriviaqa::history::1350',
  'opentriviaqa::history::1383',
  'opentriviaqa::history::1423',
  'opentriviaqa::history::1428',
  'opentriviaqa::history::1442',
  'opentriviaqa::history::1510',
  'opentriviaqa::history::1511',
  'opentriviaqa::history::1512',
  'opentriviaqa::history::1513',
  'opentriviaqa::history::1514',
  'opentriviaqa::history::1516',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bFords Theatre\b/g, "Ford's Theatre")
    .replace(/\bPeoples\b/g, "People's")
    .replace(/\bEarths\b/g, "Earth's")
    .replace(/\bBarrack Obama\b/g, 'Barack Obama')
    .replace(/\bSeminal\b/g, 'Seminole')
    .replace(/\bPearl Harbour\b/g, 'Pearl Harbor')
    .replace(/\bAdolph Hitler\b/g, 'Adolf Hitler')
    .replace(/\bKruschev\b/g, 'Khrushchev')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This choice does not match the U.S. history event, policy, conflict, institution, or era clue in the prompt.',
      'Anchor the answer to the period and the named historical development.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/revolutionary war|declaration|saratoga|kings mountain|lexington|continental congress|trenton|yorktown/.test(text)) return 'American Revolution and Founding'
  if (/civil war|gettysburg|antietam|bull run|lincoln|confederate|grant|lee/.test(text)) return 'Civil War and Reconstruction'
  if (/world war|wwii|pearl harbor|operation torch|yalta|atomic bomb|ration|war effort|normandy/.test(text)) return 'World War II and Home Front'
  if (/cold war|cuba|cuban missile|korean war|vietnam|bay of pigs|space|nasa|apollo|sputnik/.test(text)) return 'Cold War and Space Race'
  if (/patent|african american|women|teamsters|cherokee|civil rights|black history/.test(text)) return 'Social Change and Institutions'
  return 'U.S. History Anchors'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_us_history_extension_import.cjs.',
    '// Manual allowlist: APUSH-aligned event/policy/conflict rows only; excludes quote attribution, consumer trivia, local facts, and all-of-these rows.',
    '',
    "export const openTriviaUsHistoryExtensionQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${357001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(`U.S. History Extension ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed U.S. History extension micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(candidatesPath, 'utf8'))
  const rows = payload.courses['AP US History'] ?? []
  const items = rows.filter((row) => allowedSourceIds.has(row.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  for (const item of items) {
    if (item.answer_choices.some((choice) => /^all of these$/i.test(String(choice).trim()))) {
      throw new Error(`All-of-these row slipped into allowlist: ${item.source_id}`)
    }
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} U.S. History extension questions.`)
}

main()
