const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const candidatesPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaHistoryMicroImported.ts')

const usHistorySourceIds = [
  'opentriviaqa::history::37',
  'opentriviaqa::history::118',
  'opentriviaqa::history::119',
  'opentriviaqa::history::127',
  'opentriviaqa::history::128',
  'opentriviaqa::history::130',
  'opentriviaqa::history::289',
  'opentriviaqa::history::296',
  'opentriviaqa::history::302',
  'opentriviaqa::history::308',
  'opentriviaqa::history::373',
  'opentriviaqa::history::430',
  'opentriviaqa::history::431',
  'opentriviaqa::history::521',
]

const worldHistorySourceIds = [
  'opentriviaqa::history::12',
  'opentriviaqa::history::18',
  'opentriviaqa::history::34',
  'opentriviaqa::history::35',
  'opentriviaqa::history::76',
  'opentriviaqa::history::137',
  'opentriviaqa::history::138',
  'opentriviaqa::history::139',
  'opentriviaqa::history::145',
  'opentriviaqa::history::372',
  'opentriviaqa::history::442',
  'opentriviaqa::history::448',
  'opentriviaqa::history::464',
  'opentriviaqa::history::465',
  'opentriviaqa::history::466',
  'opentriviaqa::history::480',
  'opentriviaqa::history::489',
  'opentriviaqa::history::515',
  'opentriviaqa::history::601',
  'opentriviaqa::history::604',
  'opentriviaqa::history::607',
  'opentriviaqa::history::608',
  'opentriviaqa::history::619',
  'opentriviaqa::history::624',
  'opentriviaqa::history::656',
  'opentriviaqa::history::675',
  'opentriviaqa::history::676',
  'opentriviaqa::history::702',
]

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function chapterForPrompt(prompt, track) {
  if (track === 'US History') {
    if (/Civil War|Bull Run|Antietam|Stonewall|Fort Wagner/i.test(prompt)) return 'U.S. Civil War'
    if (/Vietnam|Korean|Pearl Harbour|Second World War|WWII|World War II|Eisenhower|Marshall/i.test(prompt)) return 'U.S. and Global Conflict'
    if (/Aztec|Cortes|Veracruz|Columbus/i.test(prompt)) return 'Colonial Encounters'
    return 'U.S. History Anchors'
  }

  if (/Rome|Punic|Triumvirate|Alexander|Crusade|Byzantine|Constantinople|Maya|Aztec|Inca|Indus/i.test(prompt)) return 'Ancient and Medieval Worlds'
  if (/French Revolution|Napoleon|Industrial Revolution|Opium|Scramble for Africa|European Union|Maastricht|Hong Kong|Japan|samurai/i.test(prompt)) return 'Revolutions, Empires, and Modernity'
  if (/World War|WWI|WWII|Kursk|Sea Lion|Russo-Japanese/i.test(prompt)) return 'Global Conflict'
  return 'World History Anchors'
}

function buildQuestion(item, id, track) {
  const prompt = normalizeText(item.prompt)
  const wrong = wrongChoices(item)
  if (wrong.length < 2) throw new Error(`Not enough wrong choices for ${item.source_id}`)
  return [
    '  {',
    `    id: ${id},`,
    `    chapter: ${JSON.stringify(chapterForPrompt(prompt, track))},`,
    `    title: ${JSON.stringify(prompt.length <= 58 ? prompt : `OpenTrivia ${track} ${id}`)},`,
    `    prompt: ${JSON.stringify(prompt)},`,
    `    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`,
    `    wrong: ${JSON.stringify(wrong.map((choice) => [choice, 'This choice does not match the event, period, leader, empire, or conflict clue in the prompt.', 'Anchor on the historical period and the named development rather than the closest-sounding option.']))},`,
    `    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed ${track} micro-batch.`)},`,
    "    source: 'OpenTriviaQA',",
    '  },',
  ].join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(candidatesPath, 'utf8'))
  const rows = Object.values(payload.courses ?? {}).flat()
  const bySourceId = new Map(rows.map((row) => [row.source_id, row]))
  const usRows = usHistorySourceIds.map((sourceId) => bySourceId.get(sourceId))
  const worldRows = worldHistorySourceIds.map((sourceId) => bySourceId.get(sourceId))
  if ([...usRows, ...worldRows].some((row) => !row)) throw new Error('One or more reviewed history source ids were not found.')

  let nextId = 341001
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_history_micro_import.cjs from the reviewed history candidate report.',
    '// Small stable AP History anchor batch only; broad quote/trivia/current-history rows remain in review reports.',
    '',
    "export const openTriviaHistoryQuestions = makeQuestionBank('AP', [",
    ...usRows.map((item) => buildQuestion(item, nextId++, 'US History')),
    ...worldRows.map((item) => buildQuestion(item, nextId++, 'World History')),
    '])',
    '',
  ]

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8')
  console.log(`Wrote ${usRows.length} U.S. history and ${worldRows.length} world history OpenTriviaQA questions.`)
}

main()
