const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const candidatesPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaWorldHistoryExtensionImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::history::140',
  'opentriviaqa::history::151',
  'opentriviaqa::history::153',
  'opentriviaqa::history::154',
  'opentriviaqa::history::157',
  'opentriviaqa::history::178',
  'opentriviaqa::history::223',
  'opentriviaqa::history::236',
  'opentriviaqa::history::243',
  'opentriviaqa::history::273',
  'opentriviaqa::history::278',
  'opentriviaqa::history::309',
  'opentriviaqa::history::330',
  'opentriviaqa::history::463',
  'opentriviaqa::history::467',
  'opentriviaqa::history::492',
  'opentriviaqa::history::497',
  'opentriviaqa::history::511',
  'opentriviaqa::history::517',
  'opentriviaqa::history::546',
  'opentriviaqa::history::568',
  'opentriviaqa::history::599',
  'opentriviaqa::history::600',
  'opentriviaqa::history::733',
  'opentriviaqa::history::741',
  'opentriviaqa::history::748',
  'opentriviaqa::history::754',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bEnglands\b/g, "England's")
    .replace(/\bGreat Poland Uprising\b/g, 'Greater Poland Uprising')
    .replace(/\bSubstraction\b/g, 'Subtraction')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This choice does not match the period, civilization, conflict, revolution, or institution named in the prompt.',
      'Anchor on the historical development and its place in the wider survey timeline.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/rome|roman|crusade|byzantine|alexander|darius|hastings|normans|lares/.test(text)) return 'Ancient and Medieval Worlds'
  if (/french revolution|napoleon|industrial revolution|russian revolution|mensheviks|opium|crimean|lisbon|bastille/.test(text)) return 'Revolutions and Industrial Empires'
  if (/european union|european economic community|maastricht|cold war|berlin wall|east and west|soviet/.test(text)) return 'Cold War and European Integration'
  if (/holocaust|world war|wwi|wwii|germany invaded|battle/.test(text)) return 'Global Conflict'
  if (/achaemenid|zoroastrianism|rome founded|india|rebellion|persian/.test(text)) return 'Civilizations and Belief Systems'
  return 'World History Anchors'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_world_history_extension_import.cjs.',
    '// Manual allowlist: AP World/History survey rows only; excludes weapons trivia and narrow commander/personality recall.',
    '',
    "export const openTriviaWorldHistoryExtensionQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${355001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(`World History Extension ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed World History extension micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(candidatesPath, 'utf8'))
  const rows = payload.courses['AP World History'] ?? []
  const items = rows.filter((row) => allowedSourceIds.has(row.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} World History extension questions.`)
}

main()
