const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const rawPath = path.join(repoRoot, 'data/raw_collections/opentriviaqa/opentriviaqa_questions.json')
const auditPath = path.join(repoRoot, 'reports/opentrivia-for-kids-mapping-audit.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaForKidsImported.ts')

const trackIdMap = {
  'col-arithmetic': 'arithmetic',
  'col-times-tables': 'timesTables',
  'col-money-basics': 'moneyBasics',
  'col-basic-geometry-and-measurement': 'basicGeometry',
  'col-class-5-math': 'class5Math',
  'col-class-6-math': 'class6Math',
  'col-4th-grade-reading-and-vocab': 'readingVocab4th',
  'col-5th-grade-reading-and-vocab': 'readingVocab5th',
  scienceYear1: 'scienceYear1',
  oceanPrimary: 'oceanPrimary',
  scienceYear3: 'scienceYear3',
}

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function chapterForTrack(trackId) {
  if (trackId === 'arithmetic') return 'Arithmetic Practice'
  if (trackId === 'timesTables') return 'Multiplication Facts'
  if (trackId === 'moneyBasics') return 'Money Word Problems'
  if (trackId === 'basicGeometry') return 'Measurement and Geometry'
  if (trackId === 'class5Math') return 'Class 5 Mixed Maths'
  if (trackId === 'class6Math') return 'Class 6 Mixed Maths'
  if (trackId === 'readingVocab4th') return 'Antonyms and Vocabulary'
  if (trackId === 'readingVocab5th') return 'Grammar and Vocabulary'
  if (trackId === 'oceanPrimary') return 'Ocean Animals'
  if (trackId === 'scienceYear3') return 'Plants and Earth Science'
  return 'Primary Science'
}

function rationaleForTrack(trackId, choice) {
  if (trackId.includes('Math') || ['arithmetic', 'timesTables', 'moneyBasics', 'basicGeometry'].includes(trackId)) {
    return [choice, 'This choice does not match the arithmetic, measurement, or word-problem relationship in the prompt.', 'Work through the quantities step by step before choosing.']
  }
  if (trackId.includes('readingVocab')) {
    return [choice, 'This word does not fit the vocabulary relationship being tested.', 'Check whether the prompt asks for an opposite, grammar role, or word meaning.']
  }
  return [choice, 'This choice does not match the science clue in the prompt.', 'Use the observable feature, habitat, or basic science fact named in the question.']
}

function titleForItem(item, index) {
  const prompt = normalizeText(item.prompt_text)
  if (prompt.length <= 58) return prompt
  return `OpenTrivia For Kids ${index + 1}`
}

function main() {
  const raw = JSON.parse(fs.readFileSync(rawPath, 'utf8')).items ?? []
  const rawBySourceId = new Map(raw.map((item) => [item.source_id, item]))
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const byTrack = {}

  for (const course of audit.mappedCourses ?? []) {
    const trackId = trackIdMap[course.courseId]
    if (!trackId) continue
    for (const sourceId of course.sourceIds ?? []) {
      const item = rawBySourceId.get(sourceId)
      if (!item) continue
      const wrong = wrongChoices(item)
      if (wrong.length < 2) continue
      byTrack[trackId] ??= []
      byTrack[trackId].push(item)
    }
  }

  let nextId = 337001
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_for_kids_import.cjs from data/raw_collections/opentriviaqa.',
    '// Uses the reviewed for-kids allowlist and drops binary true/false rows with fewer than two distractors.',
    '',
    'export const openTriviaForKidsQuestionsByTrack = {',
  ]

  for (const [trackId, items] of Object.entries(byTrack).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${JSON.stringify(trackId)}: makeQuestionBank('Primary', [`)
    items.forEach((item, index) => {
      const wrong = wrongChoices(item)
      lines.push('    {')
      lines.push(`      id: ${nextId++},`)
      lines.push(`      chapter: ${JSON.stringify(chapterForTrack(trackId))},`)
      lines.push(`      title: ${JSON.stringify(titleForItem(item, index))},`)
      lines.push(`      prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
      lines.push(`      correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
      lines.push(`      wrong: ${JSON.stringify(wrong.map((choice) => rationaleForTrack(trackId, choice)))},`)
      lines.push(`      lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). This row came from the reviewed for-kids allowlist for ${trackId}.`)},`)
      lines.push("      source: 'OpenTriviaQA',")
      lines.push('    },')
    })
    lines.push('  ]),')
  }

  lines.push('}')
  lines.push('')
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8')
  const total = Object.values(byTrack).reduce((sum, items) => sum + items.length, 0)
  console.log(`Wrote ${total} OpenTriviaQA for-kids questions across ${Object.keys(byTrack).length} tracks.`)
}

main()
