const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-animals-science-technology-audit.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaMolecularBiologyImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::science-technology::344',
  'opentriviaqa::science-technology::346',
  'opentriviaqa::science-technology::497',
  'opentriviaqa::science-technology::498',
  'opentriviaqa::science-technology::499',
  'opentriviaqa::science-technology::500',
  'opentriviaqa::science-technology::501',
  'opentriviaqa::science-technology::502',
  'opentriviaqa::science-technology::503',
  'opentriviaqa::science-technology::504',
  'opentriviaqa::science-technology::505',
  'opentriviaqa::science-technology::507',
  'opentriviaqa::science-technology::508',
  'opentriviaqa::science-technology::991',
  'opentriviaqa::science-technology::998',
  'opentriviaqa::science-technology::1000',
  'opentriviaqa::science-technology::1193',
  'opentriviaqa::science-technology::1194',
  'opentriviaqa::science-technology::1197',
  'opentriviaqa::science-technology::1198',
  'opentriviaqa::science-technology::1199',
  'opentriviaqa::science-technology::1200',
  'opentriviaqa::science-technology::1330',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bDeoxyribo-Nucleic\b/g, 'deoxyribonucleic')
    .replace(/\bDeoxyribonucleic\b/g, 'deoxyribonucleic')
    .replace(/\bdeoxyribonucleic Acid\b/g, 'deoxyribonucleic acid')
    .replace(/\bRibonucleic\b/g, 'ribonucleic')
    .replace(/^deoxyribonucleic acid/g, 'Deoxyribonucleic acid')
    .replace(/\bflagelle\b/g, 'flagellum')
    .replace(/\bcellogy\b/g, 'cell biology')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This choice does not match the molecular biology, cell biology, genetics, or evolution clue in the prompt.',
      'Anchor the answer to DNA/RNA, heredity, cell structure, biotechnology, or evolutionary mechanism.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt_text} ${item.correct_answer}`.toLowerCase()
  if (/dna|rna|nucleotide|gene|chromosome|genome|allele|replication|transcription|restriction|pcr|retrovirus/.test(text)) {
    return 'Molecular Genetics and Biotechnology'
  }
  if (/golgi|mitochondria|eukaryotic|cell|cytology/.test(text)) return 'Cell Biology'
  if (/evolution|vestigial|atavism|peppered moth|darwin|finch|punctuated/.test(text)) return 'Evolution and Natural Selection'
  return 'AP Biology Foundations'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_molecular_biology_import.cjs.',
    '// Manual allowlist: AP Biology molecular genetics, cell biology, biotechnology, and evolution rows only.',
    '',
    "export const openTriviaMolecularBiologyQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${358001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(`Molecular Biology ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed AP Biology molecular/cell/evolution micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const items = audit.acceptedCandidates.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP Biology molecular/cell/evolution questions.`)
}

main()
