const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const candidatesPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaArtPhilosophyMicroImported.ts')

const artHistorySourceIds = [
  'opentriviaqa::history::639',
  'opentriviaqa::history::643',
  'opentriviaqa::history::647',
  'opentriviaqa::history::1251',
  'opentriviaqa::humanities::338',
  'opentriviaqa::humanities::339',
  'opentriviaqa::humanities::718',
  'opentriviaqa::humanities::721',
  'opentriviaqa::humanities::829',
  'opentriviaqa::humanities::831',
  'opentriviaqa::humanities::832',
  'opentriviaqa::humanities::839',
  'opentriviaqa::humanities::891',
  'opentriviaqa::humanities::921',
  'opentriviaqa::humanities::925',
  'opentriviaqa::humanities::928',
]

const philosophySourceIds = [
  'opentriviaqa::history::1397',
  'opentriviaqa::humanities::1019',
  'opentriviaqa::humanities::1020',
  'opentriviaqa::humanities::1021',
  'opentriviaqa::humanities::1022',
  'opentriviaqa::humanities::1024',
]

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function chapterForArt(prompt) {
  if (/Michelangelo|Renaissance|Donatello|Ghiberti|Vitruvius|Palladio|Leonardo/i.test(prompt)) return 'Renaissance Art and Architecture'
  if (/Impressionism|Monet|Degas|Pissarro/i.test(prompt)) return 'Modern Art Movements'
  if (/Gothic|Baroque|Rembrandt|watercolor|Cubism/i.test(prompt)) return 'Styles and Techniques'
  return 'Art History Foundations'
}

function chapterForPhilosophy(prompt) {
  if (/Categorical Imperative|morality|Ockham|sovereign|social contract/i.test(prompt)) return 'Ethics and Political Philosophy'
  if (/analytic philosophy|Academy|will to power/i.test(prompt)) return 'Major Philosophers'
  return 'Philosophy Foundations'
}

function buildQuestion(item, id, target) {
  const prompt = normalizeText(item.prompt)
  const wrong = wrongChoices(item)
  if (wrong.length < 2) throw new Error(`Not enough wrong choices for ${item.source_id}`)
  const isArt = target === 'artHistory'
  return [
    '  {',
    `    id: ${id},`,
    `    chapter: ${JSON.stringify(isArt ? chapterForArt(prompt) : chapterForPhilosophy(prompt))},`,
    `    title: ${JSON.stringify(prompt.length <= 58 ? prompt : `OpenTrivia ${isArt ? 'Art History' : 'Philosophy'} ${id}`)},`,
    `    prompt: ${JSON.stringify(prompt)},`,
    `    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`,
    `    wrong: ${JSON.stringify(wrong.map((choice) => [choice, isArt ? 'This choice does not match the artist, artwork, movement, or technique named in the prompt.' : 'This choice does not match the philosopher, concept, or school of thought named in the prompt.', isArt ? 'Use the art-history clue: artist, period, medium, movement, or named work.' : 'Use the philosophical clue: doctrine, work, method, or named thinker.']))},`,
    `    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed ${isArt ? 'art-history' : 'philosophy'} micro-batch.`)},`,
    "    source: 'OpenTriviaQA',",
    '  },',
  ].join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(candidatesPath, 'utf8'))
  const rows = Object.values(payload.courses ?? {}).flat()
  const bySourceId = new Map(rows.map((row) => [row.source_id, row]))
  const artRows = artHistorySourceIds.map((sourceId) => bySourceId.get(sourceId))
  const philosophyRows = philosophySourceIds.map((sourceId) => bySourceId.get(sourceId))
  if ([...artRows, ...philosophyRows].some((row) => !row)) {
    throw new Error('One or more reviewed art/philosophy source ids were not found.')
  }

  let nextId = 340001
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_art_philosophy_micro_import.cjs from the reviewed humanities candidate report.',
    '// Small stable art-history and philosophy micro-batch only; broad humanities trivia remains in review reports.',
    '',
    "export const openTriviaArtHistoryQuestions = makeQuestionBank('University', [",
    ...artRows.map((item) => buildQuestion(item, nextId++, 'artHistory')),
    '])',
    '',
    "export const openTriviaPhilosophyQuestions = makeQuestionBank('University', [",
    ...philosophyRows.map((item) => buildQuestion(item, nextId++, 'philosophy')),
    '])',
    '',
  ]

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8')
  console.log(`Wrote ${artRows.length} art-history and ${philosophyRows.length} philosophy OpenTriviaQA questions.`)
}

main()
