const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-animals-science-technology-audit.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaApcsExtensionImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::science-technology::380',
  'opentriviaqa::science-technology::1001',
  'opentriviaqa::science-technology::1054',
  'opentriviaqa::science-technology::1057',
  'opentriviaqa::science-technology::1296',
  'opentriviaqa::science-technology::1369',
  'opentriviaqa::science-technology::2160',
  'opentriviaqa::science-technology::2167',
  'opentriviaqa::science-technology::2342',
])

const titleOverrides = {
  'opentriviaqa::science-technology::380': 'Web Cookies',
  'opentriviaqa::science-technology::1001': 'Output Devices',
  'opentriviaqa::science-technology::1054': 'Logic Programming',
  'opentriviaqa::science-technology::1057': 'The C Programming Language',
  'opentriviaqa::science-technology::1296': 'Terabits',
  'opentriviaqa::science-technology::1369': 'Fortran',
  'opentriviaqa::science-technology::2160': 'Ada',
  'opentriviaqa::science-technology::2167': 'C',
  'opentriviaqa::science-technology::2342': 'Linear Programming',
}

function normalizeText(value, sourceId) {
  let text = String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/a web pages program/g, "a web page's program")
    .replace(/girls name/g, "girl's name")
    .replace(/also a the name/g, 'also the name')
    .trim()
  if (sourceId === 'opentriviaqa::science-technology::1057' && text === 'DMR') return 'Dennis Ritchie'
  if (sourceId === 'opentriviaqa::science-technology::1057') {
    text = text.replace('by BWK and what other computer scientist?', 'by Brian Kernighan and what other computer scientist?')
  }
  if (sourceId === 'opentriviaqa::science-technology::1296') {
    text = text.replace('Many computer drives have a capacity of a terabit. How many bits are in one terabit?', 'How many bits are in one terabit?')
  }
  if (sourceId === 'opentriviaqa::science-technology::2160') {
    text = text.replace("Which girl's name is also the name of a computer programming language?", 'Which name is also the name of a computer programming language?')
  }
  return text
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer, item.source_id).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map((choice) => normalizeText(choice, item.source_id))
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This option does not match the computing concept or programming-history clue in the prompt.',
      'Identify whether the question is about web state, devices, programming languages, units, or algorithms.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt_text} ${item.correct_answer}`.toLowerCase()
  if (/cookie|output device|speaker/.test(text)) return 'Computer Systems and the Web'
  if (/programming language|prolog|fortran|ada|language| c programming/.test(text)) return 'Programming Languages'
  if (/terabit|bits/.test(text)) return 'Data Representation'
  if (/linear programming|inequalities|dantzig/.test(text)) return 'Algorithms and Optimization'
  return 'AP Computer Science Foundations'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_apcs_extension_import.cjs.',
    '// Manual allowlist: durable AP Computer Science concept/history rows only.',
    '',
    "export const openTriviaApcsExtensionQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${360001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleOverrides[item.source_id] || `AP CS Extension ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text, item.source_id))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer, item.source_id))},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed AP Computer Science extension micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const items = audit.acceptedCandidates.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP Computer Science extension questions.`)
}

main()
