const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaLiteratureShakespeareModernistImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::literature::1134',
  'opentriviaqa::literature::1135',
  'opentriviaqa::literature::1143',
  'opentriviaqa::literature::1155',
  'opentriviaqa::literature::1156',
  'opentriviaqa::literature::1157',
  'opentriviaqa::literature::1172',
  'opentriviaqa::literature::1173',
  'opentriviaqa::literature::1196',
  'opentriviaqa::literature::1198',
  'opentriviaqa::literature::1199',
  'opentriviaqa::literature::1272',
  'opentriviaqa::literature::1274',
  'opentriviaqa::literature::1277',
  'opentriviaqa::literature::1278',
  'opentriviaqa::literature::1282',
  'opentriviaqa::literature::1283',
  'opentriviaqa::literature::1284',
  'opentriviaqa::literature::1285',
  'opentriviaqa::literature::1286',
  'opentriviaqa::literature::1287',
  'opentriviaqa::literature::1288',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bT\. S\. Eliot\b/g, 'T.S. Eliot')
    .replace(/\be e cummings\b/g, 'e. e. cummings')
    .replace(/\bMendelssohn\b/g, 'Mendelssohn')
    .replace(/\bA Midsummer Nights Dream\b/g, "A Midsummer Night's Dream")
    .replace(/\bTwelfth Night\b/g, 'Twelfth Night')
    .replace(/\bThe Winters Tale\b/g, "The Winter's Tale")
    .replace(/\bShakespeares\b/g, "Shakespeare's")
    .replace(/\bThousand?en\b/g, 'Tennyson')
    .replace(/\bDante Alighieri\b/g, 'Dante Alighieri')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => !/^(all|none) of these$/i.test(choice))
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This answer belongs to a different play, poet, or literary period.',
      'Match the named clue in the prompt to the specific work or writer being tested.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/shakespeare|hamlet|othello|merchant of venice|measure for measure|as you like it|midsummer|twelfth night|richard iii/.test(text)) return 'Shakespeare: Plays and Characters'
  if (/eliot|cummings|rossetti|stevens|plath|sylvia|millay/.test(text)) return 'Modernism and Poetry'
  if (/keats|coleridge|wordsworth|byron/.test(text)) return 'Poetry and Poets'
  if (/twain|pym|raven|ulalume/.test(text)) return 'Canonical Fiction'
  if (/brave new world|portrait of a lady/.test(text)) return 'Modern and Victorian Fiction'
  return 'AP English Literature Foundations'
}

function titleForItem(item, index) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/richard iii/.test(text)) return 'Richard III'
  if (/all the worlds a stage/.test(text)) return 'As You Like It'
  if (/hollow men/.test(text)) return 'The Hollow Men'
  if (/paul revere/.test(text)) return 'Paul Revere'
  if (/cummings/.test(text)) return 'e. e. cummings'
  if (/first fig/.test(text)) return 'First Fig'
  if (/ode on a grecian urn/.test(text)) return 'Ode on a Grecian Urn'
  if (/kubla khan/.test(text)) return 'Kubla Khan'
  if (/the raven/.test(text)) return 'The Raven'
  if (/arthur gordon pym/.test(text)) return 'Arthur Gordon Pym'
  if (/ulalume/.test(text)) return 'Ulalume'
  if (/portrait of a lady/.test(text)) return 'Portrait of a Lady'
  if (/brave new world/.test(text)) return 'Brave New World'
  if (/something is rotten/.test(text)) return 'Hamlet'
  if (/midsummer nights dream/.test(text)) return "A Midsummer Night's Dream"
  if (/in the bleak midwinter/.test(text)) return 'Christina Rossetti'
  if (/snow man/.test(text)) return 'Wallace Stevens'
  if (/twelfth night/.test(text)) return 'Twelfth Night'
  if (/claudius/.test(text)) return 'Hamlet'
  if (/merchant of venice/.test(text)) return 'The Merchant of Venice'
  if (/measure for measure/.test(text)) return 'Measure for Measure'
  if (/othello/.test(text)) return 'Othello'
  return `Modernist Literature ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_literature_shakespeare_modernist_import.cjs.',
    '// Manual allowlist: Shakespeare, modernist poets, and durable canonical author/work rows only.',
    '',
    "export const openTriviaLiteratureShakespeareModernistQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    const correct = normalizeText(item.correct_answer)
    if (/^(all|none) of these$/i.test(correct)) throw new Error(`Bad correct answer for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${364501 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item, index))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(correct)},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the AP English Literature Shakespeare/modernist micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const rows = audit.courses['AP English Literature/Humanities'] || []
  const items = rows.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP English Literature Shakespeare/modernist questions.`)
}

main()
