const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opendsa/opendsa_exercises.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openDsaSoftwareImported.ts')

const softwareCollections = new Set([
  'open-dsa::background',
  'open-dsa::design',
  'open-dsa::introtosoftwaredesign',
  'open-dsa::swdesignanddatastructs',
])

const chapterByCollection = {
  'open-dsa::background': 'Computing Background',
  'open-dsa::design': 'Software Design',
  'open-dsa::introtosoftwaredesign': 'Intro Software Design',
  'open-dsa::swdesignanddatastructs': 'Software Design and Data Structures',
}

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function jsString(value) {
  return JSON.stringify(value)
}

function wrongChoices(item) {
  const correct = normalizeText(item.solution_text).toLowerCase()
  const seen = new Set([correct])
  return (item.choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

function promptLeaksAnswer(item) {
  const prompt = normalizeText(item.prompt_text)
  const answer = normalizeText(item.solution_text)
  if (!prompt || !answer) return false
  return (
    (answer.length > 3 && prompt.toLowerCase().includes(answer.toLowerCase())) ||
    new RegExp(`(?:^|\\s)${escapeRegExp(answer)}$`, 'i').test(prompt)
  )
}

function hasTemplatePlaceholder(value) {
  return (
    /\b(?:CHOICES|CHOICESINDEX|ANSWER|RELTYPE|INDEX|FRAGMENT|VAR\w*)\b/.test(value) ||
    /\{[A-Za-z_][^}]*\}/.test(value)
  )
}

function hasCourseSpecificAdminText(item) {
  const text = [item.title, item.prompt_text, item.solution_text, ...wrongChoices(item)].map(normalizeText).join(' ')
  return (
    /\b(?:CS\s*2114|CS2114|WebCAT|Piazza|GlobeTrotters|lab sections?|course instructors?|in-person CS|support projects|course style guidelines)\b/i.test(text) ||
    /^Welcome\b/i.test(normalizeText(item.title)) ||
    /What should be done to correct the following code\?$/i.test(normalizeText(item.prompt_text))
  )
}

function isUsable(item) {
  const values = [normalizeText(item.prompt_text), normalizeText(item.solution_text), ...wrongChoices(item)]
  return (
    softwareCollections.has(item.collection_id) &&
    normalizeText(item.prompt_text) &&
    normalizeText(item.solution_text) &&
    wrongChoices(item).length >= 2 &&
    !promptLeaksAnswer(item) &&
    !hasCourseSpecificAdminText(item) &&
    values.every((value) => !hasTemplatePlaceholder(value))
  )
}

function buildWrongTriples(item) {
  return wrongChoices(item).map((choice) => [
    choice,
    'This is plausible in nearby software-design contexts, but it misses the exact rule or definition being tested.',
    'Anchor on the named concept in the prompt before choosing the closest implementation detail.',
  ])
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opendsa_software_import.cjs from data/raw_collections/opendsa.',
    '// Filters out template placeholders, local course-admin prompts, and obvious answer leakage.',
    '',
    "export const openDsaSoftwareQuestions = makeQuestionBank('Software', [",
  ]

  items.forEach((item, index) => {
    const lesson = `Source: OpenDSA (${item.source_id}). Correct answer: ${normalizeText(item.solution_text)}.`
    lines.push('  {')
    lines.push(`    id: ${331001 + index},`)
    lines.push(`    chapter: ${jsString(chapterByCollection[item.collection_id] ?? 'Software Design')},`)
    lines.push(`    title: ${jsString(normalizeText(item.title) || `OpenDSA Software ${index + 1}`)},`)
    lines.push(`    prompt: ${jsString(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${jsString(normalizeText(item.solution_text))},`)
    lines.push(`    wrong: ${jsString(buildWrongTriples(item))},`)
    lines.push(`    lesson: ${jsString(lesson)},`)
    lines.push("    source: 'OpenDSA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = (payload.items ?? []).filter(isUsable)
  if (items.length < 350) {
    throw new Error(`Expected at least 350 usable OpenDSA software questions, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} OpenDSA software questions.`)
}

main()
