const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-animals-science-technology-audit.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaEarthPhysicsMicroImported.ts')

const earthScienceSourceIds = [
  'opentriviaqa::science-technology::2',
  'opentriviaqa::science-technology::3',
  'opentriviaqa::science-technology::4',
  'opentriviaqa::science-technology::186',
  'opentriviaqa::science-technology::305',
  'opentriviaqa::science-technology::744',
  'opentriviaqa::science-technology::848',
  'opentriviaqa::science-technology::917',
  'opentriviaqa::science-technology::1060',
  'opentriviaqa::science-technology::1061',
  'opentriviaqa::science-technology::1076',
  'opentriviaqa::science-technology::1078',
  'opentriviaqa::science-technology::1527',
  'opentriviaqa::science-technology::1528',
  'opentriviaqa::science-technology::1531',
]

const physicsSourceIds = [
  'opentriviaqa::science-technology::373',
  'opentriviaqa::science-technology::593',
  'opentriviaqa::science-technology::663',
  'opentriviaqa::science-technology::666',
  'opentriviaqa::science-technology::713',
  'opentriviaqa::science-technology::716',
  'opentriviaqa::science-technology::1328',
  'opentriviaqa::science-technology::1910',
  'opentriviaqa::science-technology::1941',
  'opentriviaqa::science-technology::2475',
  'opentriviaqa::science-technology::2477',
]

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function chapterForEarth(prompt) {
  if (/cloud|atmosphere|weather|cyclone|precipitation|nimbostratus/i.test(prompt)) return 'Atmosphere and Weather'
  if (/volcano|magma|earthquake|rock/i.test(prompt)) return 'Geology and Earth Systems'
  if (/water cycle|pollution|greenhouse|ozone/i.test(prompt)) return 'Environmental Systems'
  return 'Earth Science Foundations'
}

function chapterForPhysics(prompt) {
  if (/velocity|acceleration|free-fall|gravity|orbit/i.test(prompt)) return 'Motion and Gravity'
  if (/Ampere|Ohm|photon|magnetic/i.test(prompt)) return 'Electricity and Modern Physics'
  return 'Physics Foundations'
}

function buildQuestion(item, id, target) {
  const prompt = normalizeText(item.prompt_text)
  const wrong = wrongChoices(item)
  if (wrong.length < 2) throw new Error(`Not enough wrong choices for ${item.source_id}`)
  const isEarth = target === 'earth'
  return [
    '  {',
    `    id: ${id},`,
    `    chapter: ${JSON.stringify(isEarth ? chapterForEarth(prompt) : chapterForPhysics(prompt))},`,
    `    title: ${JSON.stringify(prompt.length <= 58 ? prompt : `OpenTrivia ${isEarth ? 'Earth Science' : 'Physics'} ${id}`)},`,
    `    prompt: ${JSON.stringify(prompt)},`,
    `    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`,
    `    wrong: ${JSON.stringify(wrong.map((choice) => [choice, isEarth ? 'This choice does not match the Earth-system, atmosphere, weather, or environmental process in the prompt.' : 'This choice does not match the motion, force, electricity, gravity, or modern-physics clue in the prompt.', isEarth ? 'Use the named process or system: atmosphere, weather, geology, pollution, or water cycle.' : 'Use the physics relationship or definition named in the question.']))},`,
    `    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed ${isEarth ? 'Earth systems' : 'physics'} micro-batch.`)},`,
    "    source: 'OpenTriviaQA',",
    '  },',
  ].join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const bySourceId = new Map((audit.acceptedCandidates ?? []).map((item) => [item.source_id, item]))
  const earthRows = earthScienceSourceIds.map((sourceId) => bySourceId.get(sourceId))
  const physicsRows = physicsSourceIds.map((sourceId) => bySourceId.get(sourceId))
  if ([...earthRows, ...physicsRows].some((row) => !row)) {
    throw new Error('One or more reviewed Earth/Physics source ids were not found.')
  }

  let nextId = 342001
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_earth_physics_micro_import.cjs from the reviewed science audit.',
    '// Small stable Earth systems and AP Physics micro-batch only.',
    '',
    "export const openTriviaEarthSystemsQuestions = makeQuestionBank('University', [",
    ...earthRows.map((item) => buildQuestion(item, nextId++, 'earth')),
    '])',
    '',
    "export const openTriviaPhysicsQuestions = makeQuestionBank('AP', [",
    ...physicsRows.map((item) => buildQuestion(item, nextId++, 'physics')),
    '])',
    '',
  ]

  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8')
  console.log(`Wrote ${earthRows.length} Earth systems and ${physicsRows.length} physics OpenTriviaQA questions.`)
}

main()
