const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaArtHistoryRemainingImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::history::650',
  'opentriviaqa::humanities::276',
  'opentriviaqa::humanities::279',
  'opentriviaqa::humanities::547',
  'opentriviaqa::humanities::699',
  'opentriviaqa::humanities::704',
  'opentriviaqa::humanities::707',
  'opentriviaqa::humanities::873',
  'opentriviaqa::humanities::895',
  'opentriviaqa::humanities::924',
  'opentriviaqa::humanities::1056',
  'opentriviaqa::humanities::1057',
  'opentriviaqa::humanities::1058',
  'opentriviaqa::humanities::1060',
  'opentriviaqa::humanities::1077',
])

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => !/^(all|none) of these$/i.test(choice))
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This answer belongs to a different artist, period, or art-historical detail.',
      'Match the named clue in the prompt to the specific work, artist, or movement.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/mona lisa|da vinci|michelangelo|rembrandt|caravaggio|baroque|bernini|velazquez|leonardo/.test(text)) return 'Renaissance and Baroque'
  if (/dali|surrealism|cubism|modern/.test(text)) return 'Modern Art and Surrealism'
  if (/bushido|samurai/.test(text)) return 'Japanese Art and Culture'
  return 'AP Art History Foundations'
}

function titleForItem(item, index) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/samurai|bushido/.test(text)) return 'Bushido'
  if (/moses/.test(text)) return 'Moses'
  if (/caravaggio/.test(text)) return 'Caravaggio'
  if (/louise abbema/.test(text)) return 'Louise Abbema'
  if (/mona lisa/.test(text)) return 'Mona Lisa'
  if (/dali/.test(text)) return 'Salvador Dalí'
  if (/leonardo da vinci/.test(text)) return 'Leonardo da Vinci'
  if (/rembrandt/.test(text)) return 'Rembrandt'
  if (/pietro tacca/.test(text)) return 'Pietro Tacca'
  if (/pietro bernini/.test(text)) return 'Pietro Bernini'
  if (/ottavio leoni/.test(text)) return 'Ottavio Leoni'
  if (/diego velazquez/.test(text)) return 'Diego Velázquez'
  if (/michelangelo/.test(text)) return 'Michelangelo'
  return `Art History ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_art_history_remaining_import.cjs.',
    '// Manual allowlist: remaining stable art-history and culture rows only.',
    '',
    "export const openTriviaArtHistoryRemainingQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    const correct = normalizeText(item.correct_answer)
    if (/^(all|none) of these$/i.test(correct)) throw new Error(`Bad correct answer for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${369001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item, index))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(correct)},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the AP Art History remaining micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const rows = audit.courses['AP Art History/Philosophy'] || []
  const items = rows.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP Art History remaining questions.`)
}

main()
