const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-animals-science-technology-audit.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaPhysicsExtensionImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::science-technology::271',
  'opentriviaqa::science-technology::390',
  'opentriviaqa::science-technology::616',
  'opentriviaqa::science-technology::710',
  'opentriviaqa::science-technology::712',
  'opentriviaqa::science-technology::715',
  'opentriviaqa::science-technology::718',
  'opentriviaqa::science-technology::1839',
  'opentriviaqa::science-technology::1840',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bhurricanes\b/gi, "hurricane's")
    .replace(/\bNewtons\b/g, "Newton's")
    .replace(/\bEinsteins\b/g, "Einstein's")
    .replace(/\bdeceases\b/gi, 'decreases')
    .replace(/Depends on the on the distance/g, 'It depends on the distance')
    .replace(/What does a concave mirror do with the object that is reflected\?/g, 'What does a concave mirror do to the image of an object?')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => !/^(all|none) of these$/i.test(choice))
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This option does not match the physics concept in the prompt.',
      'Use the relevant idea from waves, gravity, electricity, rotation/acceleration, or mirrors.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt_text} ${item.correct_answer}`.toLowerCase()
  if (/wave|rayleigh|seismic/.test(text)) return 'Waves and Vibrations'
  if (/gravity|newton|principia|brans-dicke|artificial gravity|sun/.test(text)) return 'Gravity and Orbital Mechanics'
  if (/lightning|voltage|electric/.test(text)) return 'Electricity and Magnetism'
  if (/mirror|concave|convex|reflected/.test(text)) return 'Optics and Mirrors'
  return 'AP Physics Foundations'
}

function titleForItem(item) {
  const text = `${item.prompt_text} ${item.correct_answer}`.toLowerCase()
  if (/rayleigh/.test(text)) return 'Rayleigh Waves'
  if (/laws of gravity/.test(text)) return 'Newton and Gravity'
  if (/lightning/.test(text)) return 'Lightning Voltage'
  if (/principia/.test(text)) return 'Principia Mathematica'
  if (/weigh 180/.test(text)) return 'Solar Surface Gravity'
  if (/brans-dicke/.test(text)) return 'Alternative Gravity Theories'
  if (/artificial gravity/.test(text)) return 'Artificial Gravity'
  if (/convex mirror/.test(text)) return 'Convex Mirrors'
  if (/concave mirror/.test(text)) return 'Concave Mirrors'
  return 'Physics Extension'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_physics_extension_import.cjs.',
    '// Manual allowlist: stable AP Physics rows only; excludes biology/astronomy spillover and known bad mirror answer rows.',
    '',
    "export const openTriviaPhysicsExtensionQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    const correct = normalizeText(item.correct_answer)
    if (/^(all|none) of these$/i.test(correct)) throw new Error(`Bad correct answer for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${362001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt_text))},`)
    lines.push(`    correct: ${JSON.stringify(correct)},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed AP Physics extension micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const items = audit.acceptedCandidates.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP Physics extension questions.`)
}

main()
