const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const candidatesPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaLiteratureMicroImported.ts')

const literatureSourceIds = [
  'opentriviaqa::humanities::591',
  'opentriviaqa::humanities::592',
  'opentriviaqa::literature::2',
  'opentriviaqa::literature::3',
  'opentriviaqa::literature::5',
  'opentriviaqa::literature::6',
  'opentriviaqa::literature::24',
  'opentriviaqa::literature::29',
  'opentriviaqa::literature::92',
  'opentriviaqa::literature::93',
  'opentriviaqa::literature::94',
  'opentriviaqa::literature::113',
  'opentriviaqa::literature::115',
  'opentriviaqa::literature::119',
  'opentriviaqa::literature::120',
  'opentriviaqa::literature::121',
  'opentriviaqa::literature::122',
  'opentriviaqa::literature::123',
  'opentriviaqa::literature::124',
  'opentriviaqa::literature::125',
  'opentriviaqa::literature::126',
]

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return (item.answer_choices ?? [])
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
}

function chapterForPrompt(prompt) {
  if (/Shakespeare|Richard III|Merchant of Venice/i.test(prompt)) return 'Shakespeare and Drama'
  if (/poet|Leaves of Grass|Death be not proud|Sappho/i.test(prompt)) return 'Poetry and Poets'
  if (/opening line|begins with|quote|characters|novel|work/i.test(prompt)) return 'Canonical Novels and Works'
  return 'Literary Knowledge'
}

function titleForPrompt(prompt, index) {
  if (prompt.length <= 58) return prompt
  return `OpenTrivia Literature ${index + 1}`
}

function main() {
  const payload = JSON.parse(fs.readFileSync(candidatesPath, 'utf8'))
  const rows = Object.values(payload.courses ?? {}).flat()
  const bySourceId = new Map(rows.map((row) => [row.source_id, row]))
  const selected = literatureSourceIds.map((sourceId) => bySourceId.get(sourceId))
  if (selected.some((row) => !row)) throw new Error('One or more reviewed literature source ids were not found.')

  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_literature_micro_import.cjs from the reviewed literature candidate report.',
    '// Small canonical-literature micro-batch only; broad history/humanities trivia remains in review reports.',
    '',
    "export const openTriviaLiteratureQuestions = makeQuestionBank('AP', [",
  ]

  selected.forEach((item, index) => {
    const prompt = normalizeText(item.prompt)
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Not enough wrong choices for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${339001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForPrompt(prompt))},`)
    lines.push(`    title: ${JSON.stringify(titleForPrompt(prompt, index))},`)
    lines.push(`    prompt: ${JSON.stringify(prompt)},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrong.map((choice) => [choice, 'This choice does not match the author, work, character, or literary clue in the prompt.', 'Use the named text, quoted line, character clue, or literary-history marker directly.']))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed canonical literature micro-batch.`)},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  fs.writeFileSync(outputPath, lines.join('\n'), 'utf8')
  console.log(`Wrote ${selected.length} OpenTriviaQA canonical literature questions.`)
}

main()
