const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaLiteraturePoetryIdentityImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::literature::1095',
  'opentriviaqa::literature::1099',
  'opentriviaqa::literature::1101',
  'opentriviaqa::literature::1103',
  'opentriviaqa::literature::1107',
  'opentriviaqa::literature::1108',
  'opentriviaqa::literature::1109',
  'opentriviaqa::literature::1110',
  'opentriviaqa::literature::1111',
  'opentriviaqa::literature::1114',
  'opentriviaqa::literature::1119',
  'opentriviaqa::literature::1123',
  'opentriviaqa::literature::1136',
  'opentriviaqa::literature::1171',
  'opentriviaqa::literature::1181',
  'opentriviaqa::literature::1195',
  'opentriviaqa::literature::1197',
  'opentriviaqa::literature::1200',
  'opentriviaqa::literature::1202',
  'opentriviaqa::literature::1203',
  'opentriviaqa::literature::1276',
  'opentriviaqa::literature::1279',
  'opentriviaqa::literature::1281',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bT\. S\. Eliot\b/g, 'T.S. Eliot')
    .replace(/\bShakespeares\b/g, "Shakespeare's")
    .replace(/\bMendelssohn\b/g, 'Mendelssohn')
    .replace(/\bHalleys\b/g, "Halley's")
    .replace(/\bLoves Labours Lost\b/g, "Love's Labour's Lost")
    .replace(/\bI Carry Your Heart With Me\b/g, 'I Carry Your Heart with Me')
    .replace(/\bEmily Dickenson\b/g, 'Emily Dickinson')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => !/^(all|none) of these$/i.test(choice))
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This answer belongs to a different writer, poem, or literary context.',
      'Use the named clue in the prompt and match it to the specific work or author.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/eliot|plath|angelou|cummings|frost|burns|rossetti/.test(text)) return 'Modernism and Poetry'
  if (/byron|coleridge|wordsworth|keats|milton|southey/.test(text)) return 'Poetry and Poets'
  if (/shakespeare|hamlet|midsummer|twelfth night|henry iv|richard iii|merchant of venice/.test(text)) return 'Shakespeare: Plays and Characters'
  if (/poe|twain|faulkner|salinger|hemingway|jane eyre|frankenstein|moby dick|brave new world/.test(text)) return 'Canonical Fiction'
  return 'AP English Literature Foundations'
}

function titleForItem(item, index) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/wilderness of mirrors/.test(text)) return 'Gerontion'
  if (/hollow men/.test(text)) return 'The Hollow Men'
  if (/poe/.test(text) && /raven/.test(text)) return 'Edgar Allan Poe'
  if (/plath/.test(text)) return 'Sylvia Plath'
  if (/e e cummings/.test(text)) return 'e. e. cummings'
  if (/frost/.test(text)) return 'Robert Frost'
  if (/byron/.test(text)) return 'Lord Byron'
  if (/coleridge/.test(text)) return 'Samuel Taylor Coleridge'
  if (/wordsworth/.test(text)) return 'William Wordsworth'
  if (/keats/.test(text)) return 'John Keats'
  if (/milton/.test(text)) return 'John Milton'
  if (/shakespeare/.test(text) || /hamlet|midsummer|twelfth night|richard iii|merchant of venice|henry iv/.test(text)) return 'Shakespeare'
  if (/catcher in the rye/.test(text)) return 'The Catcher in the Rye'
  if (/brave new world/.test(text)) return 'Brave New World'
  if (/moby dick/.test(text)) return 'Moby-Dick'
  if (/frankenstein/.test(text)) return 'Frankenstein'
  if (/wavyly|waverly/.test(text)) return 'Sir Walter Scott'
  if (/children of the frost/.test(text)) return 'Jack London'
  return `Literature Identity ${index + 1}`
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_literature_poetry_identity_import.cjs.',
    '// Manual allowlist: poetry identifiers, canonical works, and durable author/work anchors only.',
    '',
    "export const openTriviaLiteraturePoetryIdentityQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    const wrong = wrongChoices(item)
    if (wrong.length < 2) throw new Error(`Too few wrong choices for ${item.source_id}`)
    const correct = normalizeText(item.correct_answer)
    if (/^(all|none) of these$/i.test(correct)) throw new Error(`Bad correct answer for ${item.source_id}`)
    lines.push('  {')
    lines.push(`    id: ${365001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(titleForItem(item, index))},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(correct)},`)
    lines.push(`    wrong: ${JSON.stringify(wrong)},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the AP English Literature poetry/identity micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const rows = audit.courses['AP English Literature/Humanities'] || []
  const items = rows.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP English Literature poetry/identity questions.`)
}

main()
