const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const inputPath = path.join(repoRoot, 'data/raw_collections/opensat/opensat_questions.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openSatImported.ts')

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .trim()
}

function usableParagraph(value) {
  const text = normalizeText(value)
  if (!text || text.toLowerCase() === 'null') return ''
  return text
}

function promptForItem(item) {
  const prompt = normalizeText(item.prompt_text)
  const paragraph = usableParagraph(item.paragraph_text)
  if (!paragraph) return prompt
  if (paragraph.toLowerCase().includes(prompt.toLowerCase())) return paragraph
  return `${paragraph}\n\n${prompt}`
}

function chapterForItem(item) {
  const domain = normalizeText(item.domain) || 'OpenSAT'
  const difficulty = normalizeText(item.difficulty)
  return difficulty ? `${domain} - ${difficulty}` : domain
}

function titleForItem(item, index) {
  const domain = normalizeText(item.domain) || 'OpenSAT'
  return `${domain} ${index + 1}`
}

function jsString(value) {
  return JSON.stringify(value)
}

function answerEntries(item) {
  return Object.entries(item.answer_choices ?? {}).sort(([left], [right]) => left.localeCompare(right))
}

function correctChoiceText(item) {
  return normalizeText(item.answer_choices?.[item.correct_answer])
}

function wrongTriples(item) {
  const correct = correctChoiceText(item).toLowerCase()
  const seen = new Set([correct])
  return answerEntries(item)
    .filter(([key]) => key !== item.correct_answer)
    .map(([, label]) => normalizeText(label))
    .filter((label) => {
      const key = label.toLowerCase()
      if (!label || seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((label) => [
      label,
      'This is one of the OpenSAT distractors, but it misses the specific evidence or calculation.',
      'Use the passage, grammar rule, or math relationship named in the question rather than the closest-sounding option.',
    ])
}

function validateItems(items) {
  const problems = []
  for (const item of items) {
    if (!normalizeText(item.prompt_text)) problems.push(`${item.source_id}: missing prompt`)
    if (!correctChoiceText(item)) problems.push(`${item.source_id}: missing correct answer text`)
    if (answerEntries(item).length < 2) problems.push(`${item.source_id}: fewer than two answer choices`)
    if (wrongTriples(item).length < 1) problems.push(`${item.source_id}: fewer than two distinct answer labels`)
    if (!normalizeText(item.explanation)) problems.push(`${item.source_id}: missing explanation`)
  }
  if (problems.length > 0) {
    throw new Error(`OpenSAT import validation failed:\n${problems.join('\n')}`)
  }
}

function buildQuestionLiteral(item, id, index) {
  const lesson = [
    `Source: OpenSAT (${item.source_id}).`,
    normalizeText(item.explanation),
  ].join(' ')

  return [
    '  {',
    `    id: ${id},`,
    `    chapter: ${jsString(chapterForItem(item))},`,
    `    title: ${jsString(titleForItem(item, index))},`,
    `    prompt: ${jsString(promptForItem(item))},`,
    `    correct: ${jsString(correctChoiceText(item))},`,
    `    wrong: ${jsString(wrongTriples(item))},`,
    `    lesson: ${jsString(lesson)},`,
    "    source: 'OpenSAT',",
    '  },',
  ].join('\n')
}

function buildBank(name, topic, items, baseId) {
  const lines = [`export const ${name} = makeQuestionBank(${jsString(topic)}, [`]
  items.forEach((item, index) => lines.push(buildQuestionLiteral(item, baseId + index, index)))
  lines.push('])')
  return lines.join('\n')
}

function main() {
  const payload = JSON.parse(fs.readFileSync(inputPath, 'utf8'))
  const items = payload.items ?? []
  validateItems(items)

  const mathItems = items.filter((item) => item.collection_id === 'opensat::math')
  const englishItems = items.filter((item) => item.collection_id === 'opensat::english')
  const output = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opensat_import.cjs from data/raw_collections/opensat.',
    '// Keep these questions source-traceable; edit the raw data or generator rather than hand-editing this file.',
    '',
    buildBank('openSatMathQuestions', 'Mathematics', mathItems, 320001),
    '',
    buildBank('openSatReadingWritingQuestions', 'AP', englishItems, 321001),
    '',
  ].join('\n')

  fs.writeFileSync(outputPath, output, 'utf8')
  console.log(`Wrote ${mathItems.length} SAT math and ${englishItems.length} SAT reading/writing questions.`)
}

main()
