const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaArtHistoryExtensionImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::humanities::281',
  'opentriviaqa::humanities::541',
  'opentriviaqa::humanities::719',
  'opentriviaqa::humanities::833',
  'opentriviaqa::humanities::837',
  'opentriviaqa::humanities::894',
  'opentriviaqa::humanities::896',
  'opentriviaqa::humanities::922',
  'opentriviaqa::humanities::929',
  'opentriviaqa::humanities::1055',
  'opentriviaqa::humanities::1075',
  'opentriviaqa::humanities::1076',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bLeonardos\b/g, "Leonardo's")
    .replace(/\bMichelangelos\b/g, "Michelangelo's")
    .replace(/\bRembrandts\b/g, "Rembrandt's")
    .replace(/\bMetropolian\b/g, 'Metropolitan')
    .replace(/\bGian lorenzo\b/g, 'Gian Lorenzo')
    .replace(/\bAmedio\b/g, 'Amedeo')
    .replace(/\bLe Combusier\b/g, 'Le Corbusier')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This choice does not match the movement, artist, medium, or architectural clue in the prompt.',
      'Use the specific art-history evidence: period, work, style, artist, or technique.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/renaissance|vitruvius|pacioli|golden ratio|michelangelo|leonardo/.test(text)) return 'Renaissance Art and Architecture'
  if (/baroque|bernini|velazquez|basilica/.test(text)) return 'Baroque Art'
  if (/impression|monet|pissarro|luncheon/.test(text)) return 'Impressionism and Modern Art'
  if (/metaphysical|de chirico|hopper|nighthawks/.test(text)) return 'Modern Art Movements'
  return 'Art History Foundations'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_art_history_extension_import.cjs.',
    '// Manual allowlist: stable art-history rows only; excludes Dali gossip, all-of-these answers, and narrow museum-location trivia.',
    '',
    "export const openTriviaArtHistoryExtensionQuestions = makeQuestionBank('University', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${354001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(`Art History Extension ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed Art History extension micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const sourceRows = audit.courses['AP Art History/Philosophy'] ?? []
  const items = sourceRows.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} Art History extension questions.`)
}

main()
