const fs = require('node:fs')
const path = require('node:path')

const repoRoot = path.resolve(__dirname, '..')
const auditPath = path.join(repoRoot, 'reports/opentriviaqa-history-humanities-literature-candidates.json')
const outputPath = path.join(repoRoot, 'src/data/questionCatalog/openTriviaLiteratureCanonImported.ts')

const allowedSourceIds = new Set([
  'opentriviaqa::literature::158',
  'opentriviaqa::literature::159',
  'opentriviaqa::literature::160',
  'opentriviaqa::literature::162',
  'opentriviaqa::literature::179',
  'opentriviaqa::literature::183',
  'opentriviaqa::literature::193',
  'opentriviaqa::literature::195',
  'opentriviaqa::literature::196',
  'opentriviaqa::literature::199',
  'opentriviaqa::literature::201',
  'opentriviaqa::literature::202',
  'opentriviaqa::literature::203',
  'opentriviaqa::literature::205',
  'opentriviaqa::literature::208',
  'opentriviaqa::literature::211',
  'opentriviaqa::literature::212',
  'opentriviaqa::literature::251',
  'opentriviaqa::literature::254',
  'opentriviaqa::literature::277',
])

function normalizeText(value) {
  return String(value ?? '')
    .replace(/\s+/g, ' ')
    .replace(/\bAustin\b/g, 'Austen')
    .replace(/\bdUrbervilles\b/g, "d'Urbervilles")
    .replace(/\bChatterleys\b/g, "Chatterley's")
    .replace(/\bOnes Own\b/g, "One's Own")
    .replace(/\bAint\b/g, "Ain't")
    .replace(/\bwon the the Pulitzer\b/g, 'won the Pulitzer')
    .replace(/\bMr\. Chiilg\b/g, 'Mr. Chillip')
    .replace(/\bMr\. Creadle\b/g, 'Mr. Creakle')
    .replace(/\bA Take of Two Cities\b/g, 'A Tale of Two Cities')
    .replace(/\bYoung man\b/g, 'Young Man')
    .trim()
}

function wrongChoices(item) {
  const correct = normalizeText(item.correct_answer).toLowerCase()
  const seen = new Set([correct])
  return item.answer_choices
    .map(normalizeText)
    .filter(Boolean)
    .filter((choice) => {
      const key = choice.toLowerCase()
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    .map((choice) => [
      choice,
      'This is a plausible literary reference, but it does not match the work, author, period, or character clue.',
      'Anchor the clue to the named text, period, author, or quoted line before choosing.',
    ])
}

function chapterForItem(item) {
  const text = `${item.prompt} ${item.correct_answer}`.toLowerCase()
  if (/shakespeare|macbeth|othello|hamlet|henry iv/.test(text)) return 'Shakespeare and Drama'
  if (/victorian|dickens|hardy|bronte|eliot|austen|frankenstein|mary shelley/.test(text)) return 'Victorian and Romantic Fiction'
  if (/hemingway|faulkner|fitzgerald|steinbeck|depression|jazz age/.test(text)) return 'American Modernism'
  if (/milton|dante|beowulf|chaucer|cervantes/.test(text)) return 'World and Early Literature'
  return 'Canonical Literature'
}

function buildOutput(items) {
  const lines = [
    "import { makeQuestionBank } from './base'",
    '',
    '// Generated by scripts/build_opentrivia_literature_canon_import.cjs.',
    '// Manual allowlist: durable canonical literature rows only, routed to AP English Literature.',
    '',
    "export const openTriviaLiteratureCanonQuestions = makeQuestionBank('AP', [",
  ]

  items.forEach((item, index) => {
    lines.push('  {')
    lines.push(`    id: ${353001 + index},`)
    lines.push(`    chapter: ${JSON.stringify(chapterForItem(item))},`)
    lines.push("    source: 'OpenTriviaQA',")
    lines.push(`    title: ${JSON.stringify(`Canonical Literature ${index + 1}`)},`)
    lines.push(`    prompt: ${JSON.stringify(normalizeText(item.prompt))},`)
    lines.push(`    correct: ${JSON.stringify(normalizeText(item.correct_answer))},`)
    lines.push(`    wrong: ${JSON.stringify(wrongChoices(item))},`)
    lines.push(`    lesson: ${JSON.stringify(`Source: OpenTriviaQA (${item.source_id}). Included in the reviewed AP English canonical-literature micro-batch.`)},`)
    lines.push('  },')
  })

  lines.push('])')
  lines.push('')
  return lines.join('\n')
}

function main() {
  const audit = JSON.parse(fs.readFileSync(auditPath, 'utf8'))
  const sourceRows = audit.courses['AP English Literature/Humanities'] ?? []
  const items = sourceRows.filter((item) => allowedSourceIds.has(item.source_id))
  if (items.length !== allowedSourceIds.size) {
    throw new Error(`Expected ${allowedSourceIds.size} allowlisted rows, found ${items.length}.`)
  }
  fs.writeFileSync(outputPath, buildOutput(items), 'utf8')
  console.log(`Wrote ${items.length} AP English canonical-literature questions.`)
}

main()
